// Generated by scripts/build_themes.py from assets/themes/*.json. Do not edit.
export const THEMES = [
 {
  "id": "neon_dark_blue",
  "name": "Neon Dark Blue",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#1d4ed8",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#3da9ff",
   "route_glow": "#3da9ff",
   "trail_old": "#3da9ff",
   "marker_core": "#ffffff",
   "marker_ring": "#3da9ff",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#3da9ff55",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "neon_cyan",
  "name": "Neon Cyan",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#0e7490",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#2af5ff",
   "route_glow": "#2af5ff",
   "trail_old": "#2af5ff",
   "marker_core": "#ffffff",
   "marker_ring": "#2af5ff",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#2af5ff55",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "neon_dark_purple",
  "name": "Neon Dark Purple",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#7e22ce",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#c56bff",
   "route_glow": "#c56bff",
   "trail_old": "#c56bff",
   "marker_core": "#ffffff",
   "marker_ring": "#c56bff",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#c56bff55",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "neon_dark_green",
  "name": "Neon Dark Green",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#15803d",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#39ff88",
   "route_glow": "#39ff88",
   "trail_old": "#39ff88",
   "marker_core": "#ffffff",
   "marker_ring": "#39ff88",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#39ff8855",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "neon_dark_red",
  "name": "Neon Dark Red",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#b91c1c",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#ff3b4e",
   "route_glow": "#ff3b4e",
   "trail_old": "#ff3b4e",
   "marker_core": "#ffffff",
   "marker_ring": "#ff3b4e",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#ff3b4e55",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "neon_dark_yellow",
  "name": "Neon Dark Yellow",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.12,
    "brightness": -0.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.2,
      0.12
     ],
     [
      0.55,
      0.5
     ],
     [
      1,
      0.92
     ]
    ]
   },
   {
    "node": "duotone",
    "dark": "#05060a",
    "light": "#a16207",
    "amount": 0.42
   },
   {
    "node": "color_balance",
    "shadows": [
     0.0,
     0.0,
     0.015
    ],
    "highlights": [
     0,
     0,
     0
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.42,
    "radius": 0.62,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.012
   }
  ],
  "palette": {
   "background": "#07080d",
   "route": "#ffd23f",
   "route_glow": "#ffd23f",
   "trail_old": "#ffd23f",
   "marker_core": "#ffffff",
   "marker_ring": "#ffd23f",
   "text_primary": "#f4f6ff",
   "text_secondary": "#a9b0c8",
   "card_bg": "#0b0e18cc",
   "card_border": "#ffd23f55",
   "attribution": "#c8cde0b0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 1.0,
   "marker": 1.2
  }
 },
 {
  "id": "dark",
  "name": "Dark",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.85,
    "contrast": 1.06
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.25,
      0.2
     ],
     [
      0.75,
      0.78
     ],
     [
      1,
      0.96
     ]
    ]
   },
   {
    "node": "color_balance",
    "shadows": [
     -0.004,
     0.0,
     0.012
    ],
    "preserve_luminance": true
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.3,
    "radius": 0.7,
    "softness": 0.6
   },
   {
    "node": "grain",
    "amount": 0.008
   }
  ],
  "palette": {
   "background": "#0e1014",
   "route": "#ff5c8a",
   "route_glow": "#ff5c8a",
   "trail_old": "#ff5c8a",
   "marker_core": "#ffffff",
   "marker_ring": "#ff5c8a",
   "text_primary": "#f3f4f6",
   "text_secondary": "#a3a8b3",
   "card_bg": "#14171ecc",
   "card_border": "#ffffff1a",
   "attribution": "#d0d4dcb0",
   "grid": "#ffffff10"
  },
  "glow": {
   "route": 0.6,
   "marker": 0.8
  }
 },
 {
  "id": "light",
  "name": "Light",
  "base": "light",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.9,
    "contrast": 1.02
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0.03
     ],
     [
      0.5,
      0.5
     ],
     [
      1,
      1
     ]
    ]
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.12,
    "radius": 0.8,
    "softness": 0.6
   }
  ],
  "palette": {
   "background": "#f2eef0",
   "route": "#e90064",
   "route_glow": "#ff4f9a",
   "trail_old": "#e90064",
   "marker_core": "#24191d",
   "marker_ring": "#e90064",
   "text_primary": "#24191d",
   "text_secondary": "#5c4b52",
   "card_bg": "#fff8fae6",
   "card_border": "#00000014",
   "attribution": "#24191dc8",
   "grid": "#00000012"
  },
  "glow": {
   "route": 0.35,
   "marker": 0.5
  }
 },
 {
  "id": "monochrome",
  "name": "Monochrome",
  "base": "light",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.1
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0.04
     ],
     [
      0.4,
      0.36
     ],
     [
      1,
      0.97
     ]
    ]
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.22,
    "radius": 0.7,
    "softness": 0.6
   },
   {
    "node": "grain",
    "amount": 0.01
   }
  ],
  "palette": {
   "background": "#e9e9e9",
   "route": "#111111",
   "route_glow": "#555555",
   "trail_old": "#111111",
   "marker_core": "#ffffff",
   "marker_ring": "#111111",
   "text_primary": "#111111",
   "text_secondary": "#555555",
   "card_bg": "#ffffffe0",
   "card_border": "#00000022",
   "attribution": "#111111c0",
   "grid": "#00000014"
  },
  "glow": {
   "route": 0.2,
   "marker": 0.3
  }
 },
 {
  "id": "high_contrast",
  "name": "High Contrast",
  "base": "dark",
  "grading": [
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.45,
    "brightness": -0.06
   },
   {
    "node": "tone_curve",
    "points": [
     [
      0,
      0
     ],
     [
      0.35,
      0.2
     ],
     [
      0.7,
      0.85
     ],
     [
      1,
      1
     ]
    ]
   }
  ],
  "post": [],
  "palette": {
   "background": "#000000",
   "route": "#ffe600",
   "route_glow": "#ffe600",
   "trail_old": "#ffe600",
   "marker_core": "#000000",
   "marker_ring": "#ffe600",
   "text_primary": "#ffffff",
   "text_secondary": "#ffffff",
   "card_bg": "#000000e6",
   "card_border": "#ffffffff",
   "attribution": "#ffffffe6",
   "grid": "#ffffff22"
  },
  "glow": {
   "route": 0.25,
   "marker": 0.4
  }
 },
 {
  "id": "experimental_blueprint",
  "name": "Blueprint (Experimental)",
  "base": "light",
  "experimental": true,
  "grading": [
   {
    "node": "invert",
    "amount": 1.0
   },
   {
    "node": "normalize",
    "saturation": 0.0,
    "contrast": 1.2
   },
   {
    "node": "duotone",
    "dark": "#0a2a5e",
    "light": "#9cc6ff",
    "amount": 1.0
   }
  ],
  "post": [
   {
    "node": "vignette",
    "strength": 0.35,
    "radius": 0.65,
    "softness": 0.7
   },
   {
    "node": "grain",
    "amount": 0.01
   }
  ],
  "palette": {
   "background": "#0a2a5e",
   "route": "#ffffff",
   "route_glow": "#bfe0ff",
   "trail_old": "#ffffff",
   "marker_core": "#0a2a5e",
   "marker_ring": "#ffffff",
   "text_primary": "#ffffff",
   "text_secondary": "#bcd6ff",
   "card_bg": "#0a2a5ecc",
   "card_border": "#ffffff40",
   "attribution": "#ffffffb0",
   "grid": "#ffffff18"
  },
  "glow": {
   "route": 0.7,
   "marker": 0.8
  }
 }
];
