"""Generate src/i18n/android.data.js from scripts/strings_*.py (10 languages, completeness-checked)."""
import json, re, sys
sys.path.insert(0, 'scripts')
from strings_en import EN
from strings_id_es import ID, ES
from strings_fr_de_pt import FR, DE, PT
from strings_ru_ar import RU, AR
from strings_zh_ja import ZH, JA
ALL = {'en': EN, 'id': ID, 'es': ES, 'fr': FR, 'de': DE, 'pt': PT, 'ru': RU, 'ar': AR, 'zh': ZH, 'ja': JA}
ph = lambda s: sorted(set(re.findall(r'\{(\w+)\}', s)))
bad = 0
for lang, d in ALL.items():
    miss = set(EN) - set(d); extra = set(d) - set(EN)
    if miss or extra: print(lang, 'missing', sorted(miss), 'extra', sorted(extra)); bad += 1
    for k, v in d.items():
        if k in EN and ph(v) != ph(EN[k]): print(lang, k, 'placeholder mismatch', ph(v), ph(EN[k])); bad += 1
if bad: sys.exit(1)
js = '// Generated by scripts/build_android_strings.py. Do not edit.\nexport const ANDROID = ' + json.dumps(ALL, ensure_ascii=False, separators=(',', ':')) + ';\n'
open('src/i18n/android.data.js', 'w', encoding='utf-8').write(js)
print(len(EN), 'keys x', len(ALL), 'languages ->', len(js.encode()) // 1024, 'KB')
