"""Generate src/i18n/desktop.data.js: the desktop translations this app uses (10 languages).

Keys are collected by scanning src/ for t('key') / tr('key') calls, plus every month/unit/video
key (used in rendered videos). Android-only strings live in src/i18n/android.data.js.
    python scripts/build_i18n.py <desktop-i18n-dir>
"""
import json, os, re, sys, glob
SRC = sys.argv[1] if len(sys.argv) > 1 else '../src/timelinerx/i18n'
LANGS = ['en', 'id', 'es', 'fr', 'de', 'pt', 'ru', 'ar', 'zh', 'ja']
used = set()
pat = re.compile(r"""\bt[r]?\(\s*['"]([a-zA-Z0-9_.]+)['"]""")
for f in glob.glob('src/**/*.js', recursive=True):
    if f.endswith('.data.js'): continue
    used.update(pat.findall(open(f, encoding='utf-8').read()))
# keys built dynamically in the UI (prefix + value)
DYN = ('ui.camera.zoom.', 'ui.camera.ltp.', 'ui.camera.framing.', 'ui.journey.trips.', 'ui.mode.', 'ui.titles.layout.',
       'ui.titles.date.', 'ui.video.aspect.', 'ui.video.quality.', 'ui.camera.pacing.', 'tut.a.step', 'tut.i.step', 'ui.journey.source.',
       'ui.journey.outliers.', 'ui.settings.unit.', 'ui.about.node.')
out = {}
for l in LANGS:
    d = json.load(open(os.path.join(SRC, l + '.json'), encoding='utf-8'))
    out[l] = {k: v for k, v in d.items() if k in used or k.startswith(('month.', 'unit.', 'video.') + DYN)}
en_n = len(out['en'])
js = '// Generated by scripts/build_i18n.py from the desktop i18n/*.json. Do not edit.\n'
js += 'export const DESKTOP = ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n'
open('src/i18n/desktop.data.js', 'w', encoding='utf-8').write(js)
print('desktop keys used:', en_n, 'size', len(js.encode()) // 1024, 'KB')
missing = sorted(k for k in used if k not in out['en'] and not k.startswith('app.'))
if missing: print('keys not in desktop (must be in android.data.js):', len(missing))
