"""Generate src/render/themes.data.js from the desktop theme JSON files (single source of truth)."""
import json, glob, os, sys
SRC = sys.argv[1] if len(sys.argv) > 1 else '../assets/themes'
order = ['neon_dark_blue', 'neon_cyan', 'neon_dark_purple', 'neon_dark_green', 'neon_dark_red', 'neon_dark_yellow',
         'dark', 'light', 'monochrome', 'high_contrast', 'experimental_blueprint']
themes = {}
for f in glob.glob(os.path.join(SRC, '*.json')):
    d = json.load(open(f, encoding='utf-8'))
    themes[d['id']] = d
ids = [i for i in order if i in themes] + sorted(i for i in themes if i not in order)
out = '// Generated by scripts/build_themes.py from assets/themes/*.json. Do not edit.\n'
out += 'export const THEMES = ' + json.dumps([themes[i] for i in ids], ensure_ascii=False, indent=1) + ';\n'
open('src/render/themes.data.js', 'w', encoding='utf-8').write(out)
print(len(ids), 'themes:', ', '.join(ids))
