FR = {
 'app.nav.home': 'Accueil', 'app.nav.studio': 'Studio', 'app.nav.library': 'Bibliothèque', 'app.nav.settings': 'Réglages', 'app.nav.about': 'À propos',
 'app.common.back': 'Retour', 'app.common.cancel': 'Annuler', 'app.common.close': 'Fermer', 'app.common.days': 'jours', 'app.common.download': 'Télécharger',
 'app.common.points': 'points', 'app.common.remove': 'Supprimer', 'app.common.save': 'Enregistrer', 'app.common.share': 'Partager', 'app.common.trips': 'voyages',
 'app.home.live': 'RENDU EN DIRECT', 'app.home.h1a': 'Vos voyages,', 'app.home.h1b': 'en film.',
 'app.home.lede': 'Transformez votre Timeline Google en vidéo cartographique cinématographique, directement sur votre téléphone. Privé, hors ligne, sans compte.',
 'app.home.import': 'Importer la Timeline', 'app.home.demo': 'Essayer le voyage de démonstration', 'app.home.p_local': 'Reste sur votre téléphone',
 'app.home.p_account': 'Sans compte', 'app.home.p_offline': 'Fonctionne hors ligne', 'app.home.continue': 'Continuer',
 'app.home.how_title': 'Récupérer votre Timeline', 'app.home.how_body': 'Pas à pas pour Android et iPhone.', 'app.home.recent': 'Vidéos récentes',
 'app.demo.name': 'Voyage de démonstration', 'app.demo.title': 'Java · Bali · Perth',
 'app.demo.note': 'Données de démonstration synthétiques : Surabaya en train à travers Java, puis vols vers Bali et Perth.',
 'app.import.local_note': 'Le fichier est lu sur ce téléphone et n’est jamais envoyé.', 'app.import.try_other': 'Choisir un autre fichier',
 'app.import.receive_failed': 'Le fichier partagé n’a pas pu être lu.',
 'app.import.truncated': 'Le fichier s’arrête brusquement (il est peut-être incomplet). Tous les enregistrements complets avant la coupure ont été importés.',
 'app.import.skipped': '{n} enregistrements inutilisables (heure ou coordonnées manquantes) ont été ignorés.',
 'app.err.not_json': 'Ce fichier n’est pas un export de Timeline (ce n’est pas du JSON).', 'app.err.unsupported': 'Ce fichier JSON ne contient pas de données Timeline Google.',
 'app.err.no_data': 'Le fichier a été lu, mais il ne contient aucun point de localisation utilisable.', 'app.err.bad_zip': 'Le fichier ZIP est endommagé ou incomplet.',
 'app.err.no_json_in_zip': 'Le fichier ZIP ne contient aucun JSON de Timeline.', 'app.err.empty': 'Le fichier est vide.',
 'app.err.too_large': 'Le fichier est trop volumineux ou dangereux à décompresser.',
 'app.fmt.android': 'Export Android', 'app.fmt.ios': 'Export iPhone', 'app.fmt.takeout_semantic': 'Takeout (sémantique)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Votre Timeline est prête', 'app.analysis.build': 'Créer mon film',
 'app.tutorial.intro': 'Google conserve la Timeline sur votre téléphone : l’export commence donc dans les réglages du téléphone.',
 'app.tutorial.open_android': 'Ouvrez le Timeline.json enregistré avec TimelinerX, ou touchez Importer la Timeline et choisissez-le.',
 'app.tutorial.open_iphone': 'Envoyez le fichier sur votre téléphone Android, puis importez-le dans TimelinerX.',
 'app.tutorial.takeout_title': 'Ancien export Google Takeout ?',
 'app.tutorial.takeout_body': 'Le .zip de takeout.google.com (avant 2024) fonctionne tel quel, y compris Records.json et Semantic Location History.',
 'app.studio.empty': 'Importez une Timeline pour commencer votre film.', 'app.studio.updating': 'Mise à jour…',
 'app.studio.world_fallback': 'L’aperçu utilise la carte Offline World car aucune clé CARTO n’est définie.', 'app.studio.replace': 'Remplacer la Timeline',
 'app.studio.render': 'Rendu',
 'app.tab.journey': 'Voyage', 'app.tab.camera': 'Caméra', 'app.tab.look': 'Style', 'app.tab.titles': 'Titres', 'app.tab.video': 'Vidéo',
 'app.journey.last7': '7 derniers jours', 'app.journey.last30': '30 derniers jours', 'app.journey.src_semantic': 'Sémantique', 'app.journey.src_detailed': 'Détaillée',
 'app.journey.empty_period': 'Aucun point sur cette période. Choisissez des dates comprises dans votre Timeline.',
 'app.camera.fine': 'Réglages fins', 'app.look.theme': 'Thème', 'app.look.trail': 'Tracé et marqueur', 'app.look.film': 'Rendu cinéma',
 'app.map.auto': 'Automatique', 'app.map.auto_carto': 'Rues CARTO (votre clé est définie)', 'app.map.auto_world': 'Offline World tant qu’aucune clé CARTO n’est ajoutée',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Côtes, frontières et noms de villes stockés sur le téléphone. Sans internet ni clé.',
 'app.map.carto': 'CARTO (selon le thème)', 'app.map.carto_desc': 'Carte des rues détaillée, claire ou sombre selon le thème.',
 'app.map.carto_nokey': 'Nécessite une clé API CARTO gratuite (Réglages).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Carte des rues colorée.',
 'app.map.plain': 'Uni', 'app.map.plain_desc': 'Pas de carte, seulement une grille de coordonnées. Minimal et hors ligne.', 'app.map.xyz': 'Serveur de tuiles personnalisé',
 'app.map.add_key': 'Ajouter une clé CARTO', 'app.map.labels': 'Noms des villes',
 'app.titles.ribbon': 'Ruban des dates',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Fil', 'app.video.hw': 'encodeur matériel',
 'app.video.4k_warn': 'La 4K demande beaucoup de mémoire. Sur ce téléphone, 1080p ou 1440p est un choix plus sûr.',
 'app.video.calm': 'Calme ≈ {s}', 'app.video.lively': 'Dynamique ≈ {s}',
 'app.audio.desc': 'Votre propre musique (MP3, AAC, WAV, OGG, FLAC). Elle boucle si elle est plus courte que la vidéo et s’estompe à la fin.',
 'app.audio.pick': 'Choisir une musique', 'app.audio.bad': 'Ce fichier audio n’a pas pu être décodé.',
 'app.render.title': 'Rendu de votre film', 'app.render.s_plan': 'Planification de la caméra', 'app.render.s_tiles': 'Préparation des tuiles de carte',
 'app.render.s_audio': 'Mixage de la bande-son', 'app.render.s_frames': 'Rendu et encodage des images', 'app.render.s_saving': 'Enregistrement dans la galerie',
 'app.render.eta': 'encore {t}', 'app.render.keep_open': '{w}×{h} à {fps} i/s. Gardez TimelinerX ouvert jusqu’à la fin. L’écran reste allumé.',
 'app.render.cancel_q': 'Arrêter le rendu ?', 'app.render.cancel_yes': 'Arrêter', 'app.render.cancel_no': 'Continuer le rendu',
 'app.render.done_title': 'Votre film est prêt', 'app.render.saved_gallery': 'Enregistré dans Galerie › Movies › TimelinerX.',
 'app.render.saved_browser': 'Prêt. Téléchargez ou partagez le MP4.', 'app.render.speed': 'vitesse de rendu', 'app.render.open_player': 'Ouvrir dans le lecteur vidéo',
 'app.render.back_studio': 'Retour au Studio', 'app.render.cancelled': 'Rendu arrêté', 'app.render.failed': 'Échec du rendu', 'app.render.retry': 'Réessayer',
 'app.render.no_encoder': 'Ce téléphone ne peut pas encoder de vidéo à cette taille. Choisissez une résolution ou une cadence plus basse.',
 'app.render.nokey_title': 'CARTO nécessite une clé API',
 'app.render.nokey_body': 'Sans clé, CARTO marque chaque tuile « API KEY REQUIRED ». Ajoutez une clé gratuite dans Réglages ou faites le rendu avec la carte Offline World.',
 'app.render.use_world': 'Utiliser la carte Offline World', 'app.render.tiles_failed_title': 'Des tuiles de carte manquent',
 'app.render.tiles_failed_body': '{n} tuiles sur {total} n’ont pas pu être téléchargées. Vérifiez votre connexion ou continuez avec un fond uni à ces endroits.',
 'app.render.continue_placeholder': 'Continuer quand même',
 'app.library.sub': 'Films rendus sur ce téléphone.', 'app.library.empty': 'Aucun film pour l’instant. Réalisez le premier dans le Studio.',
 'app.library.reuse': 'Réutiliser ces réglages', 'app.library.remove_q': 'Supprimer cette vidéo ?', 'app.library.remove_file': 'Supprimer du téléphone et de la bibliothèque',
 'app.library.remove_entry': 'Retirer seulement de la bibliothèque', 'app.library.delete_failed': 'La vidéo n’a pas pu être supprimée.',
 'app.library.applied': 'Réglages chargés dans le Studio.',
 'app.settings.key_note': 'CARTO marque « API KEY REQUIRED » sur les tuiles demandées sans clé. Les clés sont gratuites pour un usage personnel, de recherche et associatif. Votre clé reste uniquement sur ce téléphone.',
 'app.settings.save_verify': 'Enregistrer et vérifier', 'app.settings.get_key': 'Obtenir une clé gratuite', 'app.settings.key_empty': 'Saisissez d’abord une clé.',
 'app.settings.key_ok': 'Clé vérifiée : CARTO renvoie des tuiles propres.', 'app.settings.key_rejected': 'CARTO a refusé la clé (HTTP {code}).',
 'app.settings.key_unreachable': 'Impossible de joindre CARTO pour vérifier la clé. La clé est enregistrée.',
 'app.settings.key_watermarked': 'CARTO renvoie encore des tuiles filigranées avec cette clé. Elle est peut-être inactive ou restreinte.',
 'app.settings.xyz': 'Serveur de tuiles personnalisé',
 'app.settings.xyz_note': 'Facultatif. Toute source raster XYZ en HTTPS que vous avez le droit d’utiliser. Respectez sa politique d’utilisation et son attribution.',
 'app.settings.xyz_url': 'Modèle d’URL des tuiles', 'app.settings.xyz_attr': 'Texte d’attribution', 'app.settings.tile_cache': '{n} tuiles en cache sur ce téléphone',
 'app.settings.projects': 'Projets', 'app.settings.export_project': 'Exporter .nrproj', 'app.settings.import_project': 'Importer .nrproj',
 'app.settings.projects_note': 'Les fichiers de projet sont compatibles avec TimelinerX pour Windows. La Timeline elle-même n’y figure jamais.',
 'app.settings.device': 'Ce téléphone', 'app.settings.model': 'Modèle', 'app.settings.hw': 'matériel ✓', 'app.settings.sw': 'logiciel ✓',
 'app.settings.unsupported': 'non pris en charge', 'app.settings.reset': 'Réinitialiser l’app', 'app.settings.reset_q': 'Réinitialiser TimelinerX ?',
 'app.settings.reset_body': 'Supprime la Timeline importée, le projet et la liste de la bibliothèque. Les vidéos déjà dans votre galerie sont conservées.',
 'app.settings.project_loaded': 'Projet chargé.',
 'app.about.tagline': 'TimelinerX transforme votre Timeline Google en vidéo cartographique cinématographique, entièrement sur votre téléphone.',
 'app.about.privacy': 'Sans compte, sans envoi, sans pistage. Votre Timeline est lue sur ce téléphone et jamais modifiée. Seules des tuiles de carte sont téléchargées, et uniquement avec une carte en ligne.',
 'app.about.detail.import': 'Lit les exports Timeline Android et iPhone ainsi que les ZIP Google Takeout en flux, pour que les gros fichiers restent légers. Les fichiers endommagés conservent chaque enregistrement complet.',
 'app.about.detail.journey': 'Choisit la période, supprime les sauts GPS et découpe l’itinéraire en épisodes locaux et longs trajets. Les vols deviennent des arcs.',
 'app.about.detail.camera': 'Planifie chaque image de la caméra : style de zoom, cadrage à l’arrivée, temps par trajet, puis vitesse à l’écran régulière. Le même moteur que l’app de bureau.',
 'app.about.detail.tiles': 'La carte Offline World sur le téléphone, ou les tuiles CARTO avec votre clé. Chaque tuile passe par l’étalonnage du thème.',
 'app.about.detail.frames': 'Dessine chaque image : carte, trajet parcouru, tracé lumineux, le marqueur (un avion en vol), les titres et le ruban des dates.',
 'app.about.detail.encode': 'Encodage H.264 matériel via Android MediaCodec, écrit directement sur le stockage pour que même les longs films 4K tiennent.',
 'app.about.detail.verify': 'Le MP4 arrive dans Galerie › Movies › TimelinerX et dans la bibliothèque de l’app avec une miniature.',
 'app.about.credits': 'L’analyse de la Timeline, la projection et le cadrage caméra reposent sur Google Timeline Visualizer de mahlernim (MIT). Données cartographiques © contributeurs OpenStreetMap © CARTO. Carte hors ligne issue de Natural Earth (domaine public). Polices Outfit et Instrument Sans (SIL OFL). Réalisé avec Capacitor, Preact, fflate et mp4-muxer (MIT).',
}

DE = {
 'app.nav.home': 'Start', 'app.nav.studio': 'Studio', 'app.nav.library': 'Mediathek', 'app.nav.settings': 'Einstellungen', 'app.nav.about': 'Über',
 'app.common.back': 'Zurück', 'app.common.cancel': 'Abbrechen', 'app.common.close': 'Schließen', 'app.common.days': 'Tage', 'app.common.download': 'Herunterladen',
 'app.common.points': 'Punkte', 'app.common.remove': 'Entfernen', 'app.common.save': 'Speichern', 'app.common.share': 'Teilen', 'app.common.trips': 'Reisen',
 'app.home.live': 'LIVE-RENDER', 'app.home.h1a': 'Deine Reisen,', 'app.home.h1b': 'als Film.',
 'app.home.lede': 'Verwandle deine Google Zeitachse in ein filmreifes Kartenvideo, direkt auf dem Handy. Privat, offline nutzbar, ohne Konto.',
 'app.home.import': 'Zeitachse importieren', 'app.home.demo': 'Demo-Reise ansehen', 'app.home.p_local': 'Bleibt auf deinem Handy',
 'app.home.p_account': 'Kein Konto', 'app.home.p_offline': 'Funktioniert offline', 'app.home.continue': 'Weitermachen',
 'app.home.how_title': 'So bekommst du deine Zeitachse', 'app.home.how_body': 'Schritt für Schritt für Android und iPhone.', 'app.home.recent': 'Neueste Videos',
 'app.demo.name': 'Demo-Reise', 'app.demo.title': 'Java · Bali · Perth',
 'app.demo.note': 'Synthetische Demodaten: mit dem Zug von Surabaya quer über Java, dann Flüge nach Bali und Perth.',
 'app.import.local_note': 'Die Datei wird auf diesem Handy gelesen und nie hochgeladen.', 'app.import.try_other': 'Andere Datei wählen',
 'app.import.receive_failed': 'Die geteilte Datei konnte nicht gelesen werden.',
 'app.import.truncated': 'Die Datei endet abrupt (vielleicht unvollständig). Alle vollständigen Einträge vor dem Abbruch wurden importiert.',
 'app.import.skipped': '{n} Einträge waren unbrauchbar (Zeit oder Koordinaten fehlen) und wurden übersprungen.',
 'app.err.not_json': 'Diese Datei ist kein Zeitachsen-Export (kein JSON).', 'app.err.unsupported': 'Diese JSON-Datei enthält keine Google-Zeitachsendaten.',
 'app.err.no_data': 'Die Datei wurde gelesen, enthält aber keine brauchbaren Standortpunkte.', 'app.err.bad_zip': 'Die ZIP-Datei ist beschädigt oder unvollständig.',
 'app.err.no_json_in_zip': 'Die ZIP-Datei enthält kein Zeitachsen-JSON.', 'app.err.empty': 'Die Datei ist leer.',
 'app.err.too_large': 'Die Datei ist zu groß oder nicht sicher zu entpacken.',
 'app.fmt.android': 'Android-Export', 'app.fmt.ios': 'iPhone-Export', 'app.fmt.takeout_semantic': 'Takeout (semantisch)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Deine Zeitachse ist bereit', 'app.analysis.build': 'Meinen Film erstellen',
 'app.tutorial.intro': 'Google speichert die Zeitachse auf deinem Handy, deshalb beginnt der Export in den Handy-Einstellungen.',
 'app.tutorial.open_android': 'Öffne die gespeicherte Timeline.json mit TimelinerX oder tippe auf „Zeitachse importieren“ und wähle sie aus.',
 'app.tutorial.open_iphone': 'Schicke die Datei an dein Android-Handy und importiere sie dann in TimelinerX.',
 'app.tutorial.takeout_title': 'Alter Google-Takeout-Export?',
 'app.tutorial.takeout_body': 'Die .zip von takeout.google.com (vor 2024) funktioniert direkt, inklusive Records.json und Semantic Location History.',
 'app.studio.empty': 'Importiere eine Zeitachse, um deinen Film zu beginnen.', 'app.studio.updating': 'Wird aktualisiert…',
 'app.studio.world_fallback': 'Die Vorschau nutzt die Offline-World-Karte, weil kein CARTO-Schlüssel gesetzt ist.', 'app.studio.replace': 'Zeitachse ersetzen',
 'app.studio.render': 'Rendern',
 'app.tab.journey': 'Reise', 'app.tab.camera': 'Kamera', 'app.tab.look': 'Look', 'app.tab.titles': 'Titel', 'app.tab.video': 'Video',
 'app.journey.last7': 'Letzte 7 Tage', 'app.journey.last30': 'Letzte 30 Tage', 'app.journey.src_semantic': 'Semantisch', 'app.journey.src_detailed': 'Detailliert',
 'app.journey.empty_period': 'Keine Punkte in diesem Zeitraum. Wähle Daten innerhalb deiner Zeitachse.',
 'app.camera.fine': 'Feinabstimmung', 'app.look.theme': 'Theme', 'app.look.trail': 'Spur & Markierung', 'app.look.film': 'Film-Look',
 'app.map.auto': 'Automatisch', 'app.map.auto_carto': 'CARTO-Straßen (dein Schlüssel ist gesetzt)', 'app.map.auto_world': 'Offline World, bis du einen CARTO-Schlüssel hinzufügst',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Küsten, Grenzen und Städtenamen direkt auf dem Handy. Kein Internet, kein Schlüssel.',
 'app.map.carto': 'CARTO (passend zum Theme)', 'app.map.carto_desc': 'Detaillierte Straßenkarte, hell oder dunkel passend zum Theme.',
 'app.map.carto_nokey': 'Benötigt einen kostenlosen CARTO-API-Schlüssel (Einstellungen).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Farbige Straßenkarte.',
 'app.map.plain': 'Schlicht', 'app.map.plain_desc': 'Keine Karte, nur ein Koordinatengitter. Minimal und offline.', 'app.map.xyz': 'Eigener Kachelserver',
 'app.map.add_key': 'CARTO-Schlüssel hinzufügen', 'app.map.labels': 'Städtenamen',
 'app.titles.ribbon': 'Datumsleiste',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Feed', 'app.video.hw': 'Hardware-Encoder',
 'app.video.4k_warn': '4K braucht viel Speicher. Auf diesem Handy ist 1080p oder 1440p die sicherere Wahl.',
 'app.video.calm': 'Ruhig ≈ {s}', 'app.video.lively': 'Lebhaft ≈ {s}',
 'app.audio.desc': 'Deine eigene Musik (MP3, AAC, WAV, OGG, FLAC). Sie wird wiederholt, wenn sie kürzer als das Video ist, und am Ende ausgeblendet.',
 'app.audio.pick': 'Musik wählen', 'app.audio.bad': 'Diese Audiodatei konnte nicht dekodiert werden.',
 'app.render.title': 'Dein Film wird gerendert', 'app.render.s_plan': 'Kamera wird geplant', 'app.render.s_tiles': 'Kartenkacheln werden vorbereitet',
 'app.render.s_audio': 'Soundtrack wird gemischt', 'app.render.s_frames': 'Bilder werden gerendert und kodiert', 'app.render.s_saving': 'Wird in der Galerie gespeichert',
 'app.render.eta': 'noch {t}', 'app.render.keep_open': '{w}×{h} mit {fps} fps. Lass TimelinerX geöffnet, bis es fertig ist. Der Bildschirm bleibt an.',
 'app.render.cancel_q': 'Rendern stoppen?', 'app.render.cancel_yes': 'Stoppen', 'app.render.cancel_no': 'Weiter rendern',
 'app.render.done_title': 'Dein Film ist fertig', 'app.render.saved_gallery': 'Gespeichert unter Galerie › Movies › TimelinerX.',
 'app.render.saved_browser': 'Fertig. Lade die MP4 herunter oder teile sie.', 'app.render.speed': 'Render-Tempo', 'app.render.open_player': 'Im Videoplayer öffnen',
 'app.render.back_studio': 'Zurück zum Studio', 'app.render.cancelled': 'Rendern gestoppt', 'app.render.failed': 'Rendern fehlgeschlagen', 'app.render.retry': 'Erneut versuchen',
 'app.render.no_encoder': 'Dieses Handy kann Video in dieser Größe nicht kodieren. Wähle eine niedrigere Auflösung oder Bildrate.',
 'app.render.nokey_title': 'CARTO braucht einen API-Schlüssel',
 'app.render.nokey_body': 'Ohne Schlüssel stempelt CARTO jede Kachel mit „API KEY REQUIRED“. Füge in den Einstellungen einen kostenlosen Schlüssel hinzu oder rendere mit der Offline-World-Karte.',
 'app.render.use_world': 'Offline-World-Karte verwenden', 'app.render.tiles_failed_title': 'Einige Kartenkacheln fehlen',
 'app.render.tiles_failed_body': '{n} von {total} Kacheln konnten nicht geladen werden. Prüfe deine Verbindung oder fahre an diesen Stellen mit schlichtem Hintergrund fort.',
 'app.render.continue_placeholder': 'Trotzdem fortfahren',
 'app.library.sub': 'Auf diesem Handy gerenderte Filme.', 'app.library.empty': 'Noch keine Filme. Rendere deinen ersten im Studio.',
 'app.library.reuse': 'Diese Einstellungen wiederverwenden', 'app.library.remove_q': 'Dieses Video entfernen?', 'app.library.remove_file': 'Vom Handy und aus der Mediathek löschen',
 'app.library.remove_entry': 'Nur aus der Mediathek entfernen', 'app.library.delete_failed': 'Das Video konnte nicht gelöscht werden.',
 'app.library.applied': 'Einstellungen ins Studio geladen.',
 'app.settings.key_note': 'CARTO stempelt „API KEY REQUIRED“ auf Kacheln, die ohne Schlüssel abgerufen werden. Schlüssel sind für private, wissenschaftliche und gemeinnützige Nutzung kostenlos. Dein Schlüssel bleibt nur auf diesem Handy.',
 'app.settings.save_verify': 'Speichern & prüfen', 'app.settings.get_key': 'Kostenlosen Schlüssel holen', 'app.settings.key_empty': 'Gib zuerst einen Schlüssel ein.',
 'app.settings.key_ok': 'Schlüssel geprüft: CARTO liefert saubere Kacheln.', 'app.settings.key_rejected': 'CARTO hat den Schlüssel abgelehnt (HTTP {code}).',
 'app.settings.key_unreachable': 'CARTO war zur Prüfung nicht erreichbar. Der Schlüssel ist gespeichert.',
 'app.settings.key_watermarked': 'CARTO liefert mit diesem Schlüssel weiterhin Kacheln mit Wasserzeichen. Er ist evtl. inaktiv oder eingeschränkt.',
 'app.settings.xyz': 'Eigener Kachelserver',
 'app.settings.xyz_note': 'Optional. Jede HTTPS-XYZ-Rasterquelle, die du nutzen darfst. Beachte ihre Nutzungsbedingungen und Quellenangabe.',
 'app.settings.xyz_url': 'Kachel-URL-Vorlage', 'app.settings.xyz_attr': 'Quellenangabe', 'app.settings.tile_cache': '{n} Kartenkacheln auf diesem Handy zwischengespeichert',
 'app.settings.projects': 'Projekte', 'app.settings.export_project': '.nrproj exportieren', 'app.settings.import_project': '.nrproj importieren',
 'app.settings.projects_note': 'Projektdateien sind mit TimelinerX für Windows kompatibel. Die Zeitachse selbst ist nie enthalten.',
 'app.settings.device': 'Dieses Handy', 'app.settings.model': 'Modell', 'app.settings.hw': 'Hardware ✓', 'app.settings.sw': 'Software ✓',
 'app.settings.unsupported': 'nicht unterstützt', 'app.settings.reset': 'App zurücksetzen', 'app.settings.reset_q': 'TimelinerX zurücksetzen?',
 'app.settings.reset_body': 'Entfernt die importierte Zeitachse, das Projekt und die Mediathek-Liste. Videos in deiner Galerie bleiben erhalten.',
 'app.settings.project_loaded': 'Projekt geladen.',
 'app.about.tagline': 'TimelinerX verwandelt deine Google Zeitachse in ein filmreifes Kartenvideo, komplett auf deinem eigenen Handy.',
 'app.about.privacy': 'Kein Konto, kein Upload, kein Tracking. Deine Zeitachse wird auf diesem Handy gelesen und nie verändert. Heruntergeladen werden nur Kartenkacheln, und nur bei einer Online-Karte.',
 'app.about.detail.import': 'Liest Zeitachsen-Exporte von Android und iPhone sowie Google-Takeout-ZIPs als Stream, damit große Dateien leicht bleiben. Beschädigte Dateien behalten jeden vollständigen Eintrag.',
 'app.about.detail.journey': 'Wählt den Zeitraum, entfernt GPS-Sprünge und teilt die Route in lokale Episoden und lange Reisen. Flüge werden zu Bögen.',
 'app.about.detail.camera': 'Plant jedes Kamerabild: Zoomstil, Ausschnitt bei der Ankunft, Zeit pro Reise, dann gleichmäßiges Tempo auf dem Bildschirm. Dieselbe Engine wie die Desktop-App.',
 'app.about.detail.tiles': 'Die Offline-World-Karte auf dem Handy oder CARTO-Kacheln mit deinem Schlüssel. Jede Kachel durchläuft das Color Grading des Themes.',
 'app.about.detail.frames': 'Zeichnet jedes Bild: Karte, zurückgelegte Route, leuchtende Spur, die Markierung (ein Flugzeug bei Flügen), Titel und die Datumsleiste.',
 'app.about.detail.encode': 'Hardware-H.264-Kodierung über Android MediaCodec, direkt in den Speicher geschrieben, damit auch lange 4K-Filme passen.',
 'app.about.detail.verify': 'Die MP4 landet unter Galerie › Movies › TimelinerX und mit Vorschaubild in der Mediathek der App.',
 'app.about.credits': 'Zeitachsen-Analyse, Projektion und Kameraführung basieren auf Google Timeline Visualizer von mahlernim (MIT). Kartendaten © OpenStreetMap-Mitwirkende © CARTO. Offline-Karte von Natural Earth (gemeinfrei). Schriften Outfit und Instrument Sans (SIL OFL). Erstellt mit Capacitor, Preact, fflate und mp4-muxer (MIT).',
}

PT = {
 'app.nav.home': 'Início', 'app.nav.studio': 'Estúdio', 'app.nav.library': 'Biblioteca', 'app.nav.settings': 'Configurações', 'app.nav.about': 'Sobre',
 'app.common.back': 'Voltar', 'app.common.cancel': 'Cancelar', 'app.common.close': 'Fechar', 'app.common.days': 'dias', 'app.common.download': 'Baixar',
 'app.common.points': 'pontos', 'app.common.remove': 'Remover', 'app.common.save': 'Salvar', 'app.common.share': 'Compartilhar', 'app.common.trips': 'viagens',
 'app.home.live': 'RENDER AO VIVO', 'app.home.h1a': 'Suas viagens,', 'app.home.h1b': 'como um filme.',
 'app.home.lede': 'Transforme sua Linha do tempo do Google em um vídeo de mapa cinematográfico, direto no celular. Privado, funciona off-line, sem conta.',
 'app.home.import': 'Importar Linha do tempo', 'app.home.demo': 'Ver a viagem de demonstração', 'app.home.p_local': 'Fica no seu celular',
 'app.home.p_account': 'Sem conta', 'app.home.p_offline': 'Funciona off-line', 'app.home.continue': 'Continuar',
 'app.home.how_title': 'Como obter sua Linha do tempo', 'app.home.how_body': 'Passo a passo para Android e iPhone.', 'app.home.recent': 'Vídeos recentes',
 'app.demo.name': 'Viagem de demonstração', 'app.demo.title': 'Java · Bali · Perth',
 'app.demo.note': 'Dados de demonstração sintéticos: de Surabaya de trem por Java, depois voos para Bali e Perth.',
 'app.import.local_note': 'O arquivo é lido neste celular e nunca é enviado.', 'app.import.try_other': 'Escolher outro arquivo',
 'app.import.receive_failed': 'Não foi possível ler o arquivo compartilhado.',
 'app.import.truncated': 'O arquivo termina de repente (pode estar incompleto). Todos os registros completos antes do corte foram importados.',
 'app.import.skipped': '{n} registros não puderam ser usados (sem horário ou coordenadas) e foram ignorados.',
 'app.err.not_json': 'Este arquivo não é uma exportação da Linha do tempo (não é JSON).', 'app.err.unsupported': 'Este arquivo JSON não contém dados da Linha do tempo do Google.',
 'app.err.no_data': 'O arquivo foi lido, mas não contém pontos de localização utilizáveis.', 'app.err.bad_zip': 'O arquivo ZIP está danificado ou incompleto.',
 'app.err.no_json_in_zip': 'O arquivo ZIP não contém JSON da Linha do tempo.', 'app.err.empty': 'O arquivo está vazio.',
 'app.err.too_large': 'O arquivo é grande demais ou não é seguro descompactá-lo.',
 'app.fmt.android': 'Exportação do Android', 'app.fmt.ios': 'Exportação do iPhone', 'app.fmt.takeout_semantic': 'Takeout (semântico)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Sua Linha do tempo está pronta', 'app.analysis.build': 'Criar meu filme',
 'app.tutorial.intro': 'O Google guarda a Linha do tempo no seu celular, então a exportação começa nas configurações do aparelho.',
 'app.tutorial.open_android': 'Abra o Timeline.json salvo com o TimelinerX, ou toque em Importar Linha do tempo e escolha o arquivo.',
 'app.tutorial.open_iphone': 'Envie o arquivo para seu celular Android e depois importe no TimelinerX.',
 'app.tutorial.takeout_title': 'Exportação antiga do Google Takeout?',
 'app.tutorial.takeout_body': 'O .zip do takeout.google.com (antes de 2024) funciona como está, incluindo Records.json e Semantic Location History.',
 'app.studio.empty': 'Importe uma Linha do tempo para começar seu filme.', 'app.studio.updating': 'Atualizando…',
 'app.studio.world_fallback': 'A prévia usa o mapa Offline World porque não há chave da CARTO.', 'app.studio.replace': 'Substituir Linha do tempo',
 'app.studio.render': 'Renderizar',
 'app.tab.journey': 'Viagem', 'app.tab.camera': 'Câmera', 'app.tab.look': 'Visual', 'app.tab.titles': 'Títulos', 'app.tab.video': 'Vídeo',
 'app.journey.last7': 'Últimos 7 dias', 'app.journey.last30': 'Últimos 30 dias', 'app.journey.src_semantic': 'Semântica', 'app.journey.src_detailed': 'Detalhada',
 'app.journey.empty_period': 'Não há pontos neste período. Escolha datas dentro da sua Linha do tempo.',
 'app.camera.fine': 'Ajuste fino', 'app.look.theme': 'Tema', 'app.look.trail': 'Rastro e marcador', 'app.look.film': 'Visual de cinema',
 'app.map.auto': 'Automático', 'app.map.auto_carto': 'Ruas da CARTO (sua chave está configurada)', 'app.map.auto_world': 'Offline World até você adicionar uma chave da CARTO',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Litorais, fronteiras e nomes de cidades guardados no celular. Sem internet, sem chave.',
 'app.map.carto': 'CARTO (segue o tema)', 'app.map.carto_desc': 'Mapa de ruas detalhado, claro ou escuro conforme o tema.',
 'app.map.carto_nokey': 'Precisa de uma chave de API gratuita da CARTO (Configurações).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Mapa de ruas colorido.',
 'app.map.plain': 'Simples', 'app.map.plain_desc': 'Sem mapa, só uma grade de coordenadas. Minimalista e off-line.', 'app.map.xyz': 'Servidor de blocos próprio',
 'app.map.add_key': 'Adicionar chave da CARTO', 'app.map.labels': 'Nomes de cidades',
 'app.titles.ribbon': 'Faixa de datas',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Feed', 'app.video.hw': 'codificador de hardware',
 'app.video.4k_warn': '4K exige muita memória. Neste celular, 1080p ou 1440p é a escolha mais segura.',
 'app.video.calm': 'Tranquilo ≈ {s}', 'app.video.lively': 'Animado ≈ {s}',
 'app.audio.desc': 'Sua própria música (MP3, AAC, WAV, OGG, FLAC). Ela se repete se for mais curta que o vídeo e some gradualmente no final.',
 'app.audio.pick': 'Escolher música', 'app.audio.bad': 'Não foi possível decodificar este arquivo de áudio.',
 'app.render.title': 'Renderizando seu filme', 'app.render.s_plan': 'Planejando a câmera', 'app.render.s_tiles': 'Preparando os blocos do mapa',
 'app.render.s_audio': 'Mixando a trilha sonora', 'app.render.s_frames': 'Renderizando e codificando quadros', 'app.render.s_saving': 'Salvando na galeria',
 'app.render.eta': 'faltam {t}', 'app.render.keep_open': '{w}×{h} a {fps} fps. Mantenha o TimelinerX aberto até terminar. A tela fica ligada.',
 'app.render.cancel_q': 'Parar a renderização?', 'app.render.cancel_yes': 'Parar', 'app.render.cancel_no': 'Continuar renderizando',
 'app.render.done_title': 'Seu filme está pronto', 'app.render.saved_gallery': 'Salvo em Galeria › Movies › TimelinerX.',
 'app.render.saved_browser': 'Pronto. Baixe ou compartilhe o MP4.', 'app.render.speed': 'velocidade de render', 'app.render.open_player': 'Abrir no player de vídeo',
 'app.render.back_studio': 'Voltar ao Estúdio', 'app.render.cancelled': 'Renderização interrompida', 'app.render.failed': 'Falha na renderização', 'app.render.retry': 'Tentar de novo',
 'app.render.no_encoder': 'Este celular não consegue codificar vídeo neste tamanho. Escolha uma resolução ou taxa de quadros menor.',
 'app.render.nokey_title': 'A CARTO precisa de uma chave de API',
 'app.render.nokey_body': 'Sem chave, a CARTO carimba “API KEY REQUIRED” em cada bloco. Adicione uma chave gratuita nas Configurações ou renderize com o mapa Offline World.',
 'app.render.use_world': 'Usar o mapa Offline World', 'app.render.tiles_failed_title': 'Faltam alguns blocos do mapa',
 'app.render.tiles_failed_body': '{n} de {total} blocos do mapa não puderam ser baixados. Verifique sua conexão ou continue com fundo liso nesses trechos.',
 'app.render.continue_placeholder': 'Continuar mesmo assim',
 'app.library.sub': 'Filmes renderizados neste celular.', 'app.library.empty': 'Ainda não há filmes. Renderize o primeiro no Estúdio.',
 'app.library.reuse': 'Reutilizar estas configurações', 'app.library.remove_q': 'Remover este vídeo?', 'app.library.remove_file': 'Apagar do celular e da biblioteca',
 'app.library.remove_entry': 'Remover só da biblioteca', 'app.library.delete_failed': 'Não foi possível apagar o vídeo.',
 'app.library.applied': 'Configurações carregadas no Estúdio.',
 'app.settings.key_note': 'A CARTO carimba “API KEY REQUIRED” em blocos pedidos sem chave. As chaves são gratuitas para uso pessoal, de pesquisa e sem fins lucrativos. Sua chave fica apenas neste celular.',
 'app.settings.save_verify': 'Salvar e verificar', 'app.settings.get_key': 'Obter chave gratuita', 'app.settings.key_empty': 'Digite uma chave primeiro.',
 'app.settings.key_ok': 'Chave verificada: a CARTO retorna blocos limpos.', 'app.settings.key_rejected': 'A CARTO recusou a chave (HTTP {code}).',
 'app.settings.key_unreachable': 'Não foi possível contatar a CARTO para verificar a chave. A chave foi salva.',
 'app.settings.key_watermarked': 'A CARTO ainda retorna blocos com marca d’água com esta chave. Ela pode estar inativa ou restrita.',
 'app.settings.xyz': 'Servidor de blocos próprio',
 'app.settings.xyz_note': 'Opcional. Qualquer fonte raster XYZ via HTTPS que você tenha permissão para usar. Respeite a política de uso e a atribuição.',
 'app.settings.xyz_url': 'Modelo de URL dos blocos', 'app.settings.xyz_attr': 'Texto de atribuição', 'app.settings.tile_cache': '{n} blocos do mapa em cache neste celular',
 'app.settings.projects': 'Projetos', 'app.settings.export_project': 'Exportar .nrproj', 'app.settings.import_project': 'Importar .nrproj',
 'app.settings.projects_note': 'Os arquivos de projeto são compatíveis com o TimelinerX para Windows. A Linha do tempo nunca vai dentro.',
 'app.settings.device': 'Este celular', 'app.settings.model': 'Modelo', 'app.settings.hw': 'hardware ✓', 'app.settings.sw': 'software ✓',
 'app.settings.unsupported': 'não compatível', 'app.settings.reset': 'Redefinir o app', 'app.settings.reset_q': 'Redefinir o TimelinerX?',
 'app.settings.reset_body': 'Remove a Linha do tempo importada, o projeto e a lista da biblioteca. Os vídeos que já estão na galeria continuam lá.',
 'app.settings.project_loaded': 'Projeto carregado.',
 'app.about.tagline': 'O TimelinerX transforma sua Linha do tempo do Google em um vídeo de mapa cinematográfico, inteiramente no seu celular.',
 'app.about.privacy': 'Sem conta, sem envio, sem rastreamento. Sua Linha do tempo é lida neste celular e nunca é alterada. Só blocos de mapa são baixados, e apenas quando você usa um mapa on-line.',
 'app.about.detail.import': 'Lê exportações da Linha do tempo do Android e do iPhone e ZIPs do Google Takeout como fluxo, para que arquivos grandes fiquem leves. Arquivos danificados mantêm cada registro completo.',
 'app.about.detail.journey': 'Escolhe o período, remove saltos de GPS e divide a rota em episódios locais e viagens longas. Voos viram arcos.',
 'app.about.detail.camera': 'Planeja cada quadro da câmera: estilo de zoom, enquadramento na chegada, tempo por viagem e velocidade uniforme na tela. O mesmo motor do app para desktop.',
 'app.about.detail.tiles': 'O mapa Offline World no celular, ou blocos da CARTO com sua chave. Cada bloco passa pela gradação de cor do tema.',
 'app.about.detail.frames': 'Desenha cada quadro: mapa, rota percorrida, rastro luminoso, o marcador (um avião nos voos), títulos e a faixa de datas.',
 'app.about.detail.encode': 'Codificação H.264 por hardware via Android MediaCodec, gravada direto no armazenamento para que até filmes 4K longos caibam.',
 'app.about.detail.verify': 'O MP4 vai para Galeria › Movies › TimelinerX e para a biblioteca do app com uma miniatura.',
 'app.about.credits': 'A leitura da Linha do tempo, a projeção e o enquadramento da câmera se baseiam no Google Timeline Visualizer de mahlernim (MIT). Dados do mapa © colaboradores do OpenStreetMap © CARTO. Mapa off-line do Natural Earth (domínio público). Fontes Outfit e Instrument Sans (SIL OFL). Feito com Capacitor, Preact, fflate e mp4-muxer (MIT).',
}
