# Android-only UI strings. English is the master; every other language must cover every key
# (checked by test/i18n.test.js). Desktop strings are reused from the desktop i18n files.
EN = {
 'app.nav.home': 'Home', 'app.nav.studio': 'Studio', 'app.nav.library': 'Library', 'app.nav.settings': 'Settings', 'app.nav.about': 'About',
 'app.common.back': 'Back', 'app.common.cancel': 'Cancel', 'app.common.close': 'Close', 'app.common.days': 'days', 'app.common.download': 'Download',
 'app.common.points': 'points', 'app.common.remove': 'Remove', 'app.common.save': 'Save', 'app.common.share': 'Share', 'app.common.trips': 'trips',
 'app.home.live': 'LIVE RENDER', 'app.home.h1a': 'Your journeys,', 'app.home.h1b': 'as a film.',
 'app.home.lede': 'Turn your Google Timeline into a cinematic map video, right on your phone. Private, works offline, no account.',
 'app.home.import': 'Import Timeline', 'app.home.demo': 'Try the demo journey', 'app.home.p_local': 'Stays on your phone',
 'app.home.p_account': 'No account', 'app.home.p_offline': 'Works offline', 'app.home.continue': 'Continue',
 'app.home.how_title': 'Getting your Timeline', 'app.home.how_body': 'Step by step for Android and iPhone.', 'app.home.recent': 'Recent videos',
 'app.demo.name': 'Demo journey', 'app.demo.title': 'Java · Bali · Perth',
 'app.demo.note': 'Synthetic demo data: Surabaya by train across Java, then flights to Bali and Perth.',
 'app.import.local_note': 'Your file is read on this phone and never uploaded.', 'app.import.try_other': 'Choose another file',
 'app.import.receive_failed': 'The shared file could not be read.',
 'app.import.truncated': 'The file ends abruptly (it may be incomplete). Every complete record before the cut was imported.',
 'app.import.skipped': '{n} records could not be used (missing time or coordinates) and were skipped.',
 'app.err.not_json': 'This file is not a Timeline export (it is not JSON).', 'app.err.unsupported': 'This JSON file does not contain Google Timeline data.',
 'app.err.no_data': 'The file was read, but it contains no usable location points.', 'app.err.bad_zip': 'The ZIP file is damaged or incomplete.',
 'app.err.no_json_in_zip': 'The ZIP file contains no Timeline JSON.', 'app.err.empty': 'The file is empty.',
 'app.err.too_large': 'The file is too large or looks unsafe to unpack.',
 'app.fmt.android': 'Android export', 'app.fmt.ios': 'iPhone export', 'app.fmt.takeout_semantic': 'Takeout (Semantic)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Your Timeline is ready', 'app.analysis.build': 'Build my film',
 'app.tutorial.intro': 'Google keeps Timeline on your phone, so the export starts in your phone settings.',
 'app.tutorial.open_android': 'Open the saved Timeline.json with TimelinerX, or tap Import Timeline and pick it.',
 'app.tutorial.open_iphone': 'Send the file to your Android phone, then import it in TimelinerX.',
 'app.tutorial.takeout_title': 'Old Google Takeout export?',
 'app.tutorial.takeout_body': 'The .zip from takeout.google.com (before 2024) works as is, including Records.json and Semantic Location History.',
 'app.studio.empty': 'Import a Timeline to start your film.', 'app.studio.updating': 'Updating…',
 'app.studio.world_fallback': 'The preview uses the Offline World map because no CARTO key is set.', 'app.studio.replace': 'Replace Timeline',
 'app.studio.render': 'Render',
 'app.tab.journey': 'Journey', 'app.tab.camera': 'Camera', 'app.tab.look': 'Look', 'app.tab.titles': 'Titles', 'app.tab.video': 'Video',
 'app.journey.last7': 'Last 7 days', 'app.journey.last30': 'Last 30 days', 'app.journey.src_semantic': 'Semantic', 'app.journey.src_detailed': 'Detailed',
 'app.journey.empty_period': 'No points in this period. Choose dates inside your Timeline.',
 'app.camera.fine': 'Fine tuning', 'app.look.theme': 'Theme', 'app.look.trail': 'Trail & marker', 'app.look.film': 'Film look',
 'app.map.auto': 'Automatic', 'app.map.auto_carto': 'CARTO streets (your key is set)', 'app.map.auto_world': 'Offline World until you add a CARTO key',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Coastlines, borders and city names stored on the phone. No internet, no key.',
 'app.map.carto': 'CARTO (follows theme)', 'app.map.carto_desc': 'Detailed street map, light or dark to match the theme.',
 'app.map.carto_nokey': 'Needs a free CARTO API key (Settings).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Colourful street map.',
 'app.map.plain': 'Plain', 'app.map.plain_desc': 'No map, just a coordinate grid. Minimal and offline.', 'app.map.xyz': 'Custom tile server',
 'app.map.add_key': 'Add CARTO key', 'app.map.labels': 'City names',
 'app.titles.ribbon': 'Date ribbon',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Feed', 'app.video.hw': 'hardware encoder',
 'app.video.4k_warn': '4K needs a lot of memory. On this phone 1080p or 1440p is the safer choice.',
 'app.video.calm': 'Calm ≈ {s}', 'app.video.lively': 'Lively ≈ {s}',
 'app.audio.desc': 'Your own music (MP3, AAC, WAV, OGG, FLAC). It loops if it is shorter than the video and fades out at the end.',
 'app.audio.pick': 'Choose music', 'app.audio.bad': 'This audio file could not be decoded.',
 'app.render.title': 'Rendering your film', 'app.render.s_plan': 'Planning the camera', 'app.render.s_tiles': 'Preparing map tiles',
 'app.render.s_audio': 'Mixing the soundtrack', 'app.render.s_frames': 'Rendering and encoding frames', 'app.render.s_saving': 'Saving to the gallery',
 'app.render.eta': '{t} left', 'app.render.keep_open': '{w}×{h} at {fps} fps. Keep TimelinerX open until it finishes. The screen stays on.',
 'app.render.cancel_q': 'Stop rendering?', 'app.render.cancel_yes': 'Stop', 'app.render.cancel_no': 'Keep rendering',
 'app.render.done_title': 'Your film is ready', 'app.render.saved_gallery': 'Saved to Gallery › Movies › TimelinerX.',
 'app.render.saved_browser': 'Ready. Download or share the MP4.', 'app.render.speed': 'render speed', 'app.render.open_player': 'Open in video player',
 'app.render.back_studio': 'Back to Studio', 'app.render.cancelled': 'Render stopped', 'app.render.failed': 'Render failed', 'app.render.retry': 'Try again',
 'app.render.no_encoder': 'This phone cannot encode video at this size. Choose a lower resolution or frame rate.',
 'app.render.nokey_title': 'CARTO needs an API key',
 'app.render.nokey_body': 'Without a key CARTO stamps every tile with “API KEY REQUIRED”. Add a free key in Settings, or render with the Offline World map.',
 'app.render.use_world': 'Use the Offline World map', 'app.render.tiles_failed_title': 'Some map tiles are missing',
 'app.render.tiles_failed_body': '{n} of {total} map tiles could not be downloaded. Check your connection, or continue with a plain background in those spots.',
 'app.render.continue_placeholder': 'Continue anyway',
 'app.library.sub': 'Films rendered on this phone.', 'app.library.empty': 'No films yet. Render your first one in the Studio.',
 'app.library.reuse': 'Reuse these settings', 'app.library.remove_q': 'Remove this video?', 'app.library.remove_file': 'Delete from phone and library',
 'app.library.remove_entry': 'Remove from library only', 'app.library.delete_failed': 'The video could not be deleted.',
 'app.library.applied': 'Settings loaded into the Studio.',
 'app.settings.key_note': 'CARTO stamps “API KEY REQUIRED” on tiles requested without a key. Keys are free for personal, research and non-profit use. Your key is stored only on this phone.',
 'app.settings.save_verify': 'Save & verify', 'app.settings.get_key': 'Get a free key', 'app.settings.key_empty': 'Enter a key first.',
 'app.settings.key_ok': 'Key verified: CARTO returns clean tiles.', 'app.settings.key_rejected': 'CARTO rejected the key (HTTP {code}).',
 'app.settings.key_unreachable': 'CARTO could not be reached to verify the key. The key is saved.',
 'app.settings.key_watermarked': 'CARTO still returns watermarked tiles with this key. It may be inactive or restricted.',
 'app.settings.xyz': 'Custom tile server',
 'app.settings.xyz_note': 'Optional. Any HTTPS XYZ raster source you are allowed to use. Respect its usage policy and attribution.',
 'app.settings.xyz_url': 'Tile URL template', 'app.settings.xyz_attr': 'Attribution text', 'app.settings.tile_cache': '{n} map tiles cached on this phone',
 'app.settings.projects': 'Projects', 'app.settings.export_project': 'Export .nrproj', 'app.settings.import_project': 'Import .nrproj',
 'app.settings.projects_note': 'Project files are compatible with TimelinerX for Windows. The Timeline itself is never inside.',
 'app.settings.device': 'This phone', 'app.settings.model': 'Model', 'app.settings.hw': 'hardware ✓', 'app.settings.sw': 'software ✓',
 'app.settings.unsupported': 'not supported', 'app.settings.reset': 'Reset app', 'app.settings.reset_q': 'Reset TimelinerX?',
 'app.settings.reset_body': 'Removes the imported Timeline, the project and the library list. Videos already in your gallery stay.',
 'app.settings.project_loaded': 'Project loaded.',
 'app.about.tagline': 'TimelinerX turns your Google Timeline into a cinematic map video, entirely on your own phone.',
 'app.about.privacy': 'No account, no upload, no tracking. Your Timeline is read on this phone and never modified. Only map tiles are downloaded, and only when you use an online map.',
 'app.about.detail.import': 'Reads Android and iPhone Timeline exports and Google Takeout ZIPs as a stream, so large files stay light. Damaged files keep every complete record.',
 'app.about.detail.journey': 'Picks the period, removes GPS teleport spikes and splits the route into local episodes and long trips. Flights become arcs.',
 'app.about.detail.camera': 'Plans every camera frame: zoom style, framing on arrival, time per trip, then evens out on-screen speed. Same engine as the desktop app.',
 'app.about.detail.tiles': 'The Offline World map on the phone, or CARTO tiles with your key. Every tile is graded by the theme’s colour pipeline.',
 'app.about.detail.frames': 'Draws each frame: map, travelled route, glowing trail, the marker (a plane on flights), titles and the date ribbon.',
 'app.about.detail.encode': 'Hardware H.264 encoding through Android MediaCodec, streamed to storage so even long 4K films fit.',
 'app.about.detail.verify': 'The MP4 lands in Gallery › Movies › TimelinerX and in your in-app library with a thumbnail.',
 'app.about.credits': 'Timeline parsing, projection and camera framing build on Google Timeline Visualizer by mahlernim (MIT). Map data © OpenStreetMap contributors © CARTO. Offline map from Natural Earth (public domain). Fonts Outfit and Instrument Sans (SIL OFL). Built with Capacitor, Preact, fflate and mp4-muxer (MIT).',
}
