ID = {
 'app.nav.home': 'Beranda', 'app.nav.studio': 'Studio', 'app.nav.library': 'Pustaka', 'app.nav.settings': 'Pengaturan', 'app.nav.about': 'Tentang',
 'app.common.back': 'Kembali', 'app.common.cancel': 'Batal', 'app.common.close': 'Tutup', 'app.common.days': 'hari', 'app.common.download': 'Unduh',
 'app.common.points': 'titik', 'app.common.remove': 'Hapus', 'app.common.save': 'Simpan', 'app.common.share': 'Bagikan', 'app.common.trips': 'perjalanan',
 'app.home.live': 'RENDER LANGSUNG', 'app.home.h1a': 'Perjalananmu,', 'app.home.h1b': 'jadi film.',
 'app.home.lede': 'Ubah Google Timeline jadi video peta sinematik, langsung di HP. Privat, bisa offline, tanpa akun.',
 'app.home.import': 'Impor Timeline', 'app.home.demo': 'Coba perjalanan demo', 'app.home.p_local': 'Tetap di HP-mu',
 'app.home.p_account': 'Tanpa akun', 'app.home.p_offline': 'Bisa offline', 'app.home.continue': 'Lanjutkan',
 'app.home.how_title': 'Cara mendapatkan Timeline', 'app.home.how_body': 'Langkah demi langkah untuk Android dan iPhone.', 'app.home.recent': 'Video terbaru',
 'app.demo.name': 'Perjalanan demo', 'app.demo.title': 'Jawa · Bali · Perth',
 'app.demo.note': 'Data demo sintetis: Surabaya naik kereta melintasi Jawa, lalu terbang ke Bali dan Perth.',
 'app.import.local_note': 'File dibaca di HP ini dan tidak pernah diunggah.', 'app.import.try_other': 'Pilih file lain',
 'app.import.receive_failed': 'File yang dibagikan tidak bisa dibaca.',
 'app.import.truncated': 'File berakhir mendadak (mungkin tidak lengkap). Semua catatan utuh sebelum titik putus sudah diimpor.',
 'app.import.skipped': '{n} catatan tidak bisa dipakai (waktu atau koordinat hilang) dan dilewati.',
 'app.err.not_json': 'File ini bukan ekspor Timeline (bukan JSON).', 'app.err.unsupported': 'File JSON ini tidak berisi data Google Timeline.',
 'app.err.no_data': 'File terbaca, tetapi tidak ada titik lokasi yang bisa dipakai.', 'app.err.bad_zip': 'File ZIP rusak atau tidak lengkap.',
 'app.err.no_json_in_zip': 'File ZIP tidak berisi JSON Timeline.', 'app.err.empty': 'File kosong.',
 'app.err.too_large': 'File terlalu besar atau tidak aman untuk diekstrak.',
 'app.fmt.android': 'Ekspor Android', 'app.fmt.ios': 'Ekspor iPhone', 'app.fmt.takeout_semantic': 'Takeout (Semantik)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Timeline-mu siap', 'app.analysis.build': 'Buat filmku',
 'app.tutorial.intro': 'Google menyimpan Timeline di HP, jadi ekspor dimulai dari pengaturan HP.',
 'app.tutorial.open_android': 'Buka Timeline.json yang tersimpan dengan TimelinerX, atau ketuk Impor Timeline lalu pilih filenya.',
 'app.tutorial.open_iphone': 'Kirim file ke HP Android-mu, lalu impor di TimelinerX.',
 'app.tutorial.takeout_title': 'Punya ekspor Google Takeout lama?',
 'app.tutorial.takeout_body': 'File .zip dari takeout.google.com (sebelum 2024) langsung bisa dipakai, termasuk Records.json dan Semantic Location History.',
 'app.studio.empty': 'Impor Timeline untuk mulai membuat film.', 'app.studio.updating': 'Memperbarui…',
 'app.studio.world_fallback': 'Pratinjau memakai peta Offline World karena CARTO key belum diisi.', 'app.studio.replace': 'Ganti Timeline',
 'app.studio.render': 'Render',
 'app.tab.journey': 'Perjalanan', 'app.tab.camera': 'Kamera', 'app.tab.look': 'Tampilan', 'app.tab.titles': 'Judul', 'app.tab.video': 'Video',
 'app.journey.last7': '7 hari terakhir', 'app.journey.last30': '30 hari terakhir', 'app.journey.src_semantic': 'Semantik', 'app.journey.src_detailed': 'Detail',
 'app.journey.empty_period': 'Tidak ada titik di periode ini. Pilih tanggal di dalam rentang Timeline.',
 'app.camera.fine': 'Penyesuaian halus', 'app.look.theme': 'Tema', 'app.look.trail': 'Jejak & penanda', 'app.look.film': 'Nuansa film',
 'app.map.auto': 'Otomatis', 'app.map.auto_carto': 'Peta jalan CARTO (key sudah diisi)', 'app.map.auto_world': 'Offline World sampai kamu menambahkan CARTO key',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Garis pantai, batas negara, dan nama kota tersimpan di HP. Tanpa internet, tanpa key.',
 'app.map.carto': 'CARTO (ikut tema)', 'app.map.carto_desc': 'Peta jalan detail, terang atau gelap mengikuti tema.',
 'app.map.carto_nokey': 'Butuh CARTO API key gratis (Pengaturan).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Peta jalan berwarna.',
 'app.map.plain': 'Polos', 'app.map.plain_desc': 'Tanpa peta, hanya grid koordinat. Minimalis dan offline.', 'app.map.xyz': 'Server tile kustom',
 'app.map.add_key': 'Tambah CARTO key', 'app.map.labels': 'Nama kota',
 'app.titles.ribbon': 'Pita tanggal',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Feed', 'app.video.hw': 'encoder hardware',
 'app.video.4k_warn': '4K butuh memori besar. Di HP ini 1080p atau 1440p pilihan yang lebih aman.',
 'app.video.calm': 'Santai ≈ {s}', 'app.video.lively': 'Dinamis ≈ {s}',
 'app.audio.desc': 'Musikmu sendiri (MP3, AAC, WAV, OGG, FLAC). Diulang jika lebih pendek dari video dan memudar di akhir.',
 'app.audio.pick': 'Pilih musik', 'app.audio.bad': 'File audio ini tidak bisa didekode.',
 'app.render.title': 'Merender filmmu', 'app.render.s_plan': 'Merencanakan kamera', 'app.render.s_tiles': 'Menyiapkan tile peta',
 'app.render.s_audio': 'Mencampur soundtrack', 'app.render.s_frames': 'Merender dan meng-encode frame', 'app.render.s_saving': 'Menyimpan ke galeri',
 'app.render.eta': 'sisa {t}', 'app.render.keep_open': '{w}×{h} pada {fps} fps. Biarkan TimelinerX terbuka sampai selesai. Layar tetap menyala.',
 'app.render.cancel_q': 'Hentikan render?', 'app.render.cancel_yes': 'Hentikan', 'app.render.cancel_no': 'Lanjutkan render',
 'app.render.done_title': 'Filmmu sudah jadi', 'app.render.saved_gallery': 'Tersimpan di Galeri › Movies › TimelinerX.',
 'app.render.saved_browser': 'Siap. Unduh atau bagikan MP4-nya.', 'app.render.speed': 'kecepatan render', 'app.render.open_player': 'Buka di pemutar video',
 'app.render.back_studio': 'Kembali ke Studio', 'app.render.cancelled': 'Render dihentikan', 'app.render.failed': 'Render gagal', 'app.render.retry': 'Coba lagi',
 'app.render.no_encoder': 'HP ini tidak bisa meng-encode video pada ukuran ini. Pilih resolusi atau frame rate yang lebih rendah.',
 'app.render.nokey_title': 'CARTO butuh API key',
 'app.render.nokey_body': 'Tanpa key, CARTO memberi cap “API KEY REQUIRED” di setiap tile. Tambahkan key gratis di Pengaturan, atau render dengan peta Offline World.',
 'app.render.use_world': 'Pakai peta Offline World', 'app.render.tiles_failed_title': 'Sebagian tile peta hilang',
 'app.render.tiles_failed_body': '{n} dari {total} tile peta gagal diunduh. Cek koneksi, atau lanjutkan dengan latar polos di bagian itu.',
 'app.render.continue_placeholder': 'Tetap lanjutkan',
 'app.library.sub': 'Film yang dirender di HP ini.', 'app.library.empty': 'Belum ada film. Render film pertamamu di Studio.',
 'app.library.reuse': 'Pakai lagi pengaturan ini', 'app.library.remove_q': 'Hapus video ini?', 'app.library.remove_file': 'Hapus dari HP dan pustaka',
 'app.library.remove_entry': 'Hapus dari pustaka saja', 'app.library.delete_failed': 'Video tidak bisa dihapus.',
 'app.library.applied': 'Pengaturan dimuat ke Studio.',
 'app.settings.key_note': 'CARTO memberi cap “API KEY REQUIRED” pada tile yang diminta tanpa key. Key gratis untuk penggunaan pribadi, riset, dan nirlaba. Key hanya disimpan di HP ini.',
 'app.settings.save_verify': 'Simpan & verifikasi', 'app.settings.get_key': 'Dapatkan key gratis', 'app.settings.key_empty': 'Isi key terlebih dahulu.',
 'app.settings.key_ok': 'Key terverifikasi: CARTO mengirim tile bersih.', 'app.settings.key_rejected': 'CARTO menolak key (HTTP {code}).',
 'app.settings.key_unreachable': 'CARTO tidak bisa dihubungi untuk verifikasi. Key tetap tersimpan.',
 'app.settings.key_watermarked': 'CARTO masih mengirim tile ber-watermark dengan key ini. Key mungkin belum aktif atau dibatasi.',
 'app.settings.xyz': 'Server tile kustom',
 'app.settings.xyz_note': 'Opsional. Sumber raster XYZ HTTPS apa pun yang boleh kamu pakai. Patuhi kebijakan penggunaan dan atribusinya.',
 'app.settings.xyz_url': 'Template URL tile', 'app.settings.xyz_attr': 'Teks atribusi', 'app.settings.tile_cache': '{n} tile peta tersimpan di HP ini',
 'app.settings.projects': 'Proyek', 'app.settings.export_project': 'Ekspor .nrproj', 'app.settings.import_project': 'Impor .nrproj',
 'app.settings.projects_note': 'File proyek kompatibel dengan TimelinerX untuk Windows. Isi Timeline tidak pernah ikut di dalamnya.',
 'app.settings.device': 'HP ini', 'app.settings.model': 'Model', 'app.settings.hw': 'hardware ✓', 'app.settings.sw': 'software ✓',
 'app.settings.unsupported': 'tidak didukung', 'app.settings.reset': 'Reset aplikasi', 'app.settings.reset_q': 'Reset TimelinerX?',
 'app.settings.reset_body': 'Menghapus Timeline yang diimpor, proyek, dan daftar pustaka. Video yang sudah ada di galeri tetap aman.',
 'app.settings.project_loaded': 'Proyek dimuat.',
 'app.about.tagline': 'TimelinerX mengubah Google Timeline jadi video peta sinematik, sepenuhnya di HP-mu sendiri.',
 'app.about.privacy': 'Tanpa akun, tanpa unggah, tanpa pelacakan. Timeline dibaca di HP ini dan tidak pernah diubah. Yang diunduh hanya tile peta, dan hanya saat kamu memakai peta online.',
 'app.about.detail.import': 'Membaca ekspor Timeline Android dan iPhone serta ZIP Google Takeout secara streaming, jadi file besar tetap ringan. File rusak tetap menyimpan semua catatan yang utuh.',
 'app.about.detail.journey': 'Memilih periode, membuang lonjakan teleport GPS, dan memecah rute jadi episode lokal dan perjalanan jauh. Penerbangan menjadi busur.',
 'app.about.detail.camera': 'Merencanakan setiap frame kamera: gaya zoom, framing saat tiba, durasi per perjalanan, lalu meratakan kecepatan di layar. Mesin yang sama dengan aplikasi desktop.',
 'app.about.detail.tiles': 'Peta Offline World di HP, atau tile CARTO dengan key-mu. Setiap tile diwarnai lewat pipeline warna tema.',
 'app.about.detail.frames': 'Menggambar setiap frame: peta, rute yang dilalui, jejak bercahaya, penanda (pesawat saat terbang), judul, dan pita tanggal.',
 'app.about.detail.encode': 'Encoding H.264 hardware lewat Android MediaCodec, di-stream ke penyimpanan sehingga film 4K yang panjang pun muat.',
 'app.about.detail.verify': 'MP4 masuk ke Galeri › Movies › TimelinerX dan ke pustaka aplikasi lengkap dengan thumbnail.',
 'app.about.credits': 'Parsing Timeline, proyeksi, dan framing kamera dibangun di atas Google Timeline Visualizer karya mahlernim (MIT). Data peta © kontributor OpenStreetMap © CARTO. Peta offline dari Natural Earth (domain publik). Font Outfit dan Instrument Sans (SIL OFL). Dibuat dengan Capacitor, Preact, fflate, dan mp4-muxer (MIT).',
}

ES = {
 'app.nav.home': 'Inicio', 'app.nav.studio': 'Estudio', 'app.nav.library': 'Biblioteca', 'app.nav.settings': 'Ajustes', 'app.nav.about': 'Acerca de',
 'app.common.back': 'Atrás', 'app.common.cancel': 'Cancelar', 'app.common.close': 'Cerrar', 'app.common.days': 'días', 'app.common.download': 'Descargar',
 'app.common.points': 'puntos', 'app.common.remove': 'Quitar', 'app.common.save': 'Guardar', 'app.common.share': 'Compartir', 'app.common.trips': 'viajes',
 'app.home.live': 'RENDER EN VIVO', 'app.home.h1a': 'Tus viajes,', 'app.home.h1b': 'como una película.',
 'app.home.lede': 'Convierte tu Cronología de Google en un vídeo de mapa cinematográfico, directamente en tu teléfono. Privado, sin conexión, sin cuenta.',
 'app.home.import': 'Importar Cronología', 'app.home.demo': 'Probar el viaje de demostración', 'app.home.p_local': 'Se queda en tu teléfono',
 'app.home.p_account': 'Sin cuenta', 'app.home.p_offline': 'Funciona sin conexión', 'app.home.continue': 'Continuar',
 'app.home.how_title': 'Cómo obtener tu Cronología', 'app.home.how_body': 'Paso a paso para Android y iPhone.', 'app.home.recent': 'Vídeos recientes',
 'app.demo.name': 'Viaje de demostración', 'app.demo.title': 'Java · Bali · Perth',
 'app.demo.note': 'Datos de demostración sintéticos: Surabaya en tren por Java y después vuelos a Bali y Perth.',
 'app.import.local_note': 'El archivo se lee en este teléfono y nunca se sube.', 'app.import.try_other': 'Elegir otro archivo',
 'app.import.receive_failed': 'No se pudo leer el archivo compartido.',
 'app.import.truncated': 'El archivo termina de golpe (puede estar incompleto). Se importaron todos los registros completos anteriores al corte.',
 'app.import.skipped': '{n} registros no se pudieron usar (falta la hora o las coordenadas) y se omitieron.',
 'app.err.not_json': 'Este archivo no es una exportación de Cronología (no es JSON).', 'app.err.unsupported': 'Este archivo JSON no contiene datos de la Cronología de Google.',
 'app.err.no_data': 'Se leyó el archivo, pero no contiene puntos de ubicación utilizables.', 'app.err.bad_zip': 'El archivo ZIP está dañado o incompleto.',
 'app.err.no_json_in_zip': 'El archivo ZIP no contiene ningún JSON de Cronología.', 'app.err.empty': 'El archivo está vacío.',
 'app.err.too_large': 'El archivo es demasiado grande o no es seguro descomprimirlo.',
 'app.fmt.android': 'Exportación de Android', 'app.fmt.ios': 'Exportación de iPhone', 'app.fmt.takeout_semantic': 'Takeout (semántico)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Tu Cronología está lista', 'app.analysis.build': 'Crear mi película',
 'app.tutorial.intro': 'Google guarda la Cronología en tu teléfono, así que la exportación empieza en los ajustes del teléfono.',
 'app.tutorial.open_android': 'Abre el Timeline.json guardado con TimelinerX, o toca Importar Cronología y elígelo.',
 'app.tutorial.open_iphone': 'Envía el archivo a tu teléfono Android y luego impórtalo en TimelinerX.',
 'app.tutorial.takeout_title': '¿Tienes una exportación antigua de Google Takeout?',
 'app.tutorial.takeout_body': 'El .zip de takeout.google.com (anterior a 2024) funciona tal cual, incluidos Records.json y Semantic Location History.',
 'app.studio.empty': 'Importa una Cronología para empezar tu película.', 'app.studio.updating': 'Actualizando…',
 'app.studio.world_fallback': 'La vista previa usa el mapa Offline World porque no hay clave de CARTO.', 'app.studio.replace': 'Reemplazar Cronología',
 'app.studio.render': 'Renderizar',
 'app.tab.journey': 'Viaje', 'app.tab.camera': 'Cámara', 'app.tab.look': 'Estilo', 'app.tab.titles': 'Títulos', 'app.tab.video': 'Vídeo',
 'app.journey.last7': 'Últimos 7 días', 'app.journey.last30': 'Últimos 30 días', 'app.journey.src_semantic': 'Semántica', 'app.journey.src_detailed': 'Detallada',
 'app.journey.empty_period': 'No hay puntos en este período. Elige fechas dentro de tu Cronología.',
 'app.camera.fine': 'Ajuste fino', 'app.look.theme': 'Tema', 'app.look.trail': 'Estela y marcador', 'app.look.film': 'Aspecto de cine',
 'app.map.auto': 'Automático', 'app.map.auto_carto': 'Calles de CARTO (tu clave está configurada)', 'app.map.auto_world': 'Offline World hasta que añadas una clave de CARTO',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Costas, fronteras y nombres de ciudades guardados en el teléfono. Sin internet ni clave.',
 'app.map.carto': 'CARTO (según el tema)', 'app.map.carto_desc': 'Mapa de calles detallado, claro u oscuro según el tema.',
 'app.map.carto_nokey': 'Necesita una clave API gratuita de CARTO (Ajustes).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Mapa de calles colorido.',
 'app.map.plain': 'Liso', 'app.map.plain_desc': 'Sin mapa, solo una cuadrícula de coordenadas. Minimalista y sin conexión.', 'app.map.xyz': 'Servidor de teselas propio',
 'app.map.add_key': 'Añadir clave de CARTO', 'app.map.labels': 'Nombres de ciudades',
 'app.titles.ribbon': 'Cinta de fechas',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Feed', 'app.video.hw': 'codificador por hardware',
 'app.video.4k_warn': 'El 4K necesita mucha memoria. En este teléfono 1080p o 1440p es la opción más segura.',
 'app.video.calm': 'Tranquilo ≈ {s}', 'app.video.lively': 'Dinámico ≈ {s}',
 'app.audio.desc': 'Tu propia música (MP3, AAC, WAV, OGG, FLAC). Se repite si es más corta que el vídeo y se desvanece al final.',
 'app.audio.pick': 'Elegir música', 'app.audio.bad': 'No se pudo decodificar este archivo de audio.',
 'app.render.title': 'Renderizando tu película', 'app.render.s_plan': 'Planificando la cámara', 'app.render.s_tiles': 'Preparando las teselas del mapa',
 'app.render.s_audio': 'Mezclando la banda sonora', 'app.render.s_frames': 'Renderizando y codificando fotogramas', 'app.render.s_saving': 'Guardando en la galería',
 'app.render.eta': 'quedan {t}', 'app.render.keep_open': '{w}×{h} a {fps} fps. Mantén TimelinerX abierto hasta que termine. La pantalla permanece encendida.',
 'app.render.cancel_q': '¿Detener el renderizado?', 'app.render.cancel_yes': 'Detener', 'app.render.cancel_no': 'Seguir renderizando',
 'app.render.done_title': 'Tu película está lista', 'app.render.saved_gallery': 'Guardada en Galería › Movies › TimelinerX.',
 'app.render.saved_browser': 'Lista. Descarga o comparte el MP4.', 'app.render.speed': 'velocidad de render', 'app.render.open_player': 'Abrir en el reproductor',
 'app.render.back_studio': 'Volver al Estudio', 'app.render.cancelled': 'Renderizado detenido', 'app.render.failed': 'Error en el renderizado', 'app.render.retry': 'Reintentar',
 'app.render.no_encoder': 'Este teléfono no puede codificar vídeo a este tamaño. Elige una resolución o frecuencia de fotogramas menor.',
 'app.render.nokey_title': 'CARTO necesita una clave API',
 'app.render.nokey_body': 'Sin clave, CARTO marca cada tesela con “API KEY REQUIRED”. Añade una clave gratuita en Ajustes o renderiza con el mapa Offline World.',
 'app.render.use_world': 'Usar el mapa Offline World', 'app.render.tiles_failed_title': 'Faltan algunas teselas del mapa',
 'app.render.tiles_failed_body': 'No se pudieron descargar {n} de {total} teselas. Revisa tu conexión o continúa con un fondo liso en esas zonas.',
 'app.render.continue_placeholder': 'Continuar de todos modos',
 'app.library.sub': 'Películas renderizadas en este teléfono.', 'app.library.empty': 'Aún no hay películas. Renderiza la primera en el Estudio.',
 'app.library.reuse': 'Reutilizar estos ajustes', 'app.library.remove_q': '¿Quitar este vídeo?', 'app.library.remove_file': 'Borrar del teléfono y de la biblioteca',
 'app.library.remove_entry': 'Quitar solo de la biblioteca', 'app.library.delete_failed': 'No se pudo borrar el vídeo.',
 'app.library.applied': 'Ajustes cargados en el Estudio.',
 'app.settings.key_note': 'CARTO marca con “API KEY REQUIRED” las teselas pedidas sin clave. Las claves son gratuitas para uso personal, de investigación y sin ánimo de lucro. Tu clave solo se guarda en este teléfono.',
 'app.settings.save_verify': 'Guardar y verificar', 'app.settings.get_key': 'Obtener clave gratuita', 'app.settings.key_empty': 'Introduce una clave primero.',
 'app.settings.key_ok': 'Clave verificada: CARTO devuelve teselas limpias.', 'app.settings.key_rejected': 'CARTO rechazó la clave (HTTP {code}).',
 'app.settings.key_unreachable': 'No se pudo contactar con CARTO para verificar la clave. La clave se ha guardado.',
 'app.settings.key_watermarked': 'CARTO sigue devolviendo teselas con marca de agua con esta clave. Puede estar inactiva o restringida.',
 'app.settings.xyz': 'Servidor de teselas propio',
 'app.settings.xyz_note': 'Opcional. Cualquier fuente ráster XYZ por HTTPS que tengas permiso para usar. Respeta su política de uso y su atribución.',
 'app.settings.xyz_url': 'Plantilla de URL de teselas', 'app.settings.xyz_attr': 'Texto de atribución', 'app.settings.tile_cache': '{n} teselas en caché en este teléfono',
 'app.settings.projects': 'Proyectos', 'app.settings.export_project': 'Exportar .nrproj', 'app.settings.import_project': 'Importar .nrproj',
 'app.settings.projects_note': 'Los archivos de proyecto son compatibles con TimelinerX para Windows. La Cronología nunca va dentro.',
 'app.settings.device': 'Este teléfono', 'app.settings.model': 'Modelo', 'app.settings.hw': 'hardware ✓', 'app.settings.sw': 'software ✓',
 'app.settings.unsupported': 'no compatible', 'app.settings.reset': 'Restablecer la app', 'app.settings.reset_q': '¿Restablecer TimelinerX?',
 'app.settings.reset_body': 'Elimina la Cronología importada, el proyecto y la lista de la biblioteca. Los vídeos que ya están en tu galería se conservan.',
 'app.settings.project_loaded': 'Proyecto cargado.',
 'app.about.tagline': 'TimelinerX convierte tu Cronología de Google en un vídeo de mapa cinematográfico, todo en tu propio teléfono.',
 'app.about.privacy': 'Sin cuenta, sin subidas, sin rastreo. Tu Cronología se lee en este teléfono y nunca se modifica. Solo se descargan teselas de mapa, y solo si usas un mapa en línea.',
 'app.about.detail.import': 'Lee exportaciones de Cronología de Android e iPhone y ZIP de Google Takeout como flujo, así los archivos grandes pesan poco. Los archivos dañados conservan cada registro completo.',
 'app.about.detail.journey': 'Elige el período, elimina saltos de GPS y divide la ruta en episodios locales y viajes largos. Los vuelos se convierten en arcos.',
 'app.about.detail.camera': 'Planifica cada fotograma de la cámara: estilo de zoom, encuadre al llegar, tiempo por viaje y velocidad uniforme en pantalla. El mismo motor que la app de escritorio.',
 'app.about.detail.tiles': 'El mapa Offline World en el teléfono o teselas de CARTO con tu clave. Cada tesela pasa por la gradación de color del tema.',
 'app.about.detail.frames': 'Dibuja cada fotograma: mapa, ruta recorrida, estela luminosa, el marcador (un avión en los vuelos), títulos y la cinta de fechas.',
 'app.about.detail.encode': 'Codificación H.264 por hardware con Android MediaCodec, escrita directamente al almacenamiento para que incluso películas 4K largas quepan.',
 'app.about.detail.verify': 'El MP4 llega a Galería › Movies › TimelinerX y a la biblioteca de la app con una miniatura.',
 'app.about.credits': 'El análisis de la Cronología, la proyección y el encuadre de cámara se basan en Google Timeline Visualizer de mahlernim (MIT). Datos del mapa © colaboradores de OpenStreetMap © CARTO. Mapa sin conexión de Natural Earth (dominio público). Fuentes Outfit e Instrument Sans (SIL OFL). Hecho con Capacitor, Preact, fflate y mp4-muxer (MIT).',
}
