ZH = {
 'app.nav.home': '首页', 'app.nav.studio': '工作室', 'app.nav.library': '作品库', 'app.nav.settings': '设置', 'app.nav.about': '关于',
 'app.common.back': '返回', 'app.common.cancel': '取消', 'app.common.close': '关闭', 'app.common.days': '天', 'app.common.download': '下载',
 'app.common.points': '个点', 'app.common.remove': '移除', 'app.common.save': '保存', 'app.common.share': '分享', 'app.common.trips': '次旅程',
 'app.home.live': '实时渲染', 'app.home.h1a': '你的旅程，', 'app.home.h1b': '拍成电影。',
 'app.home.lede': '在手机上直接把 Google 时间轴变成电影感地图视频。私密、可离线、无需账号。',
 'app.home.import': '导入时间轴', 'app.home.demo': '试试演示旅程', 'app.home.p_local': '数据留在手机上',
 'app.home.p_account': '无需账号', 'app.home.p_offline': '支持离线', 'app.home.continue': '继续',
 'app.home.how_title': '如何获取时间轴', 'app.home.how_body': 'Android 和 iPhone 分步说明。', 'app.home.recent': '最近的视频',
 'app.demo.name': '演示旅程', 'app.demo.title': '爪哇 · 巴厘岛 · 珀斯',
 'app.demo.note': '合成演示数据：从泗水乘火车横穿爪哇，然后飞往巴厘岛和珀斯。',
 'app.import.local_note': '文件只在这部手机上读取，绝不上传。', 'app.import.try_other': '选择其他文件',
 'app.import.receive_failed': '无法读取分享过来的文件。',
 'app.import.truncated': '文件突然结束（可能不完整）。中断前的所有完整记录均已导入。',
 'app.import.skipped': '有 {n} 条记录因缺少时间或坐标而被跳过。',
 'app.err.not_json': '此文件不是时间轴导出文件（不是 JSON）。', 'app.err.unsupported': '此 JSON 文件不包含 Google 时间轴数据。',
 'app.err.no_data': '文件已读取，但没有可用的位置点。', 'app.err.bad_zip': 'ZIP 文件已损坏或不完整。',
 'app.err.no_json_in_zip': 'ZIP 文件中没有时间轴 JSON。', 'app.err.empty': '文件为空。',
 'app.err.too_large': '文件过大，或解压不安全。',
 'app.fmt.android': 'Android 导出', 'app.fmt.ios': 'iPhone 导出', 'app.fmt.takeout_semantic': 'Takeout（语义）', 'app.fmt.takeout_records': 'Takeout（Records）',
 'app.analysis.title': '时间轴已就绪', 'app.analysis.build': '生成我的影片',
 'app.tutorial.intro': 'Google 把时间轴保存在手机上，所以导出要从手机设置开始。',
 'app.tutorial.open_android': '用 TimelinerX 打开保存的 Timeline.json，或点“导入时间轴”并选择该文件。',
 'app.tutorial.open_iphone': '把文件发送到你的 Android 手机，然后在 TimelinerX 中导入。',
 'app.tutorial.takeout_title': '有旧的 Google Takeout 导出？',
 'app.tutorial.takeout_body': 'takeout.google.com 的 .zip（2024 年以前）可直接使用，包括 Records.json 和 Semantic Location History。',
 'app.studio.empty': '导入时间轴，开始制作你的影片。', 'app.studio.updating': '正在更新…',
 'app.studio.world_fallback': '尚未设置 CARTO 密钥，预览使用 Offline World 地图。', 'app.studio.replace': '更换时间轴',
 'app.studio.render': '渲染',
 'app.tab.journey': '旅程', 'app.tab.camera': '镜头', 'app.tab.look': '外观', 'app.tab.titles': '标题', 'app.tab.video': '视频',
 'app.journey.last7': '最近 7 天', 'app.journey.last30': '最近 30 天', 'app.journey.src_semantic': '语义', 'app.journey.src_detailed': '详细',
 'app.journey.empty_period': '此时段内没有位置点。请选择时间轴范围内的日期。',
 'app.camera.fine': '精细调整', 'app.look.theme': '主题', 'app.look.trail': '轨迹与标记', 'app.look.film': '电影质感',
 'app.map.auto': '自动', 'app.map.auto_carto': 'CARTO 街道地图（已设置密钥）', 'app.map.auto_world': '添加 CARTO 密钥前使用 Offline World',
 'app.map.world': 'Offline World', 'app.map.world_desc': '海岸线、国界和城市名称存储在手机上。无需网络，无需密钥。',
 'app.map.carto': 'CARTO（随主题）', 'app.map.carto_desc': '详细街道地图，浅色或深色与主题匹配。',
 'app.map.carto_nokey': '需要免费的 CARTO API 密钥（设置）。', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': '彩色街道地图。',
 'app.map.plain': '纯色', 'app.map.plain_desc': '无地图，仅显示经纬网格。简洁且离线。', 'app.map.xyz': '自定义瓦片服务器',
 'app.map.add_key': '添加 CARTO 密钥', 'app.map.labels': '城市名称',
 'app.titles.ribbon': '日期条',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · 抖音', 'app.video.aspect_feed': '动态', 'app.video.hw': '硬件编码器',
 'app.video.4k_warn': '4K 需要大量内存。在这部手机上选择 1080p 或 1440p 更稳妥。',
 'app.video.calm': '舒缓 ≈ {s}', 'app.video.lively': '轻快 ≈ {s}',
 'app.audio.desc': '使用你自己的音乐（MP3、AAC、WAV、OGG、FLAC）。比视频短时会循环，结尾自动淡出。',
 'app.audio.pick': '选择音乐', 'app.audio.bad': '无法解码此音频文件。',
 'app.render.title': '正在渲染你的影片', 'app.render.s_plan': '规划镜头', 'app.render.s_tiles': '准备地图瓦片',
 'app.render.s_audio': '混合配乐', 'app.render.s_frames': '渲染并编码画面', 'app.render.s_saving': '保存到相册',
 'app.render.eta': '剩余 {t}', 'app.render.keep_open': '{w}×{h}，{fps} fps。请保持 TimelinerX 打开直到完成，屏幕会保持常亮。',
 'app.render.cancel_q': '停止渲染？', 'app.render.cancel_yes': '停止', 'app.render.cancel_no': '继续渲染',
 'app.render.done_title': '影片已完成', 'app.render.saved_gallery': '已保存到 相册 › Movies › TimelinerX。',
 'app.render.saved_browser': '完成。下载或分享 MP4。', 'app.render.speed': '渲染速度', 'app.render.open_player': '在视频播放器中打开',
 'app.render.back_studio': '返回工作室', 'app.render.cancelled': '渲染已停止', 'app.render.failed': '渲染失败', 'app.render.retry': '重试',
 'app.render.no_encoder': '这部手机无法编码此尺寸的视频。请选择更低的分辨率或帧率。',
 'app.render.nokey_title': 'CARTO 需要 API 密钥',
 'app.render.nokey_body': '没有密钥时，CARTO 会在每个瓦片上加印“API KEY REQUIRED”。请在设置中添加免费密钥，或改用 Offline World 地图渲染。',
 'app.render.use_world': '使用 Offline World 地图', 'app.render.tiles_failed_title': '部分地图瓦片缺失',
 'app.render.tiles_failed_body': '{total} 个瓦片中有 {n} 个下载失败。请检查网络，或在这些位置使用纯色背景继续。',
 'app.render.continue_placeholder': '仍然继续',
 'app.library.sub': '在这部手机上渲染的影片。', 'app.library.empty': '还没有影片。去工作室渲染第一部吧。',
 'app.library.reuse': '重用这些设置', 'app.library.remove_q': '移除这个视频？', 'app.library.remove_file': '从手机和作品库中删除',
 'app.library.remove_entry': '仅从作品库移除', 'app.library.delete_failed': '无法删除视频。',
 'app.library.applied': '设置已载入工作室。',
 'app.settings.key_note': '未使用密钥请求的瓦片会被 CARTO 加印“API KEY REQUIRED”。个人、研究和非营利用途可免费申请密钥。密钥只保存在这部手机上。',
 'app.settings.save_verify': '保存并验证', 'app.settings.get_key': '获取免费密钥', 'app.settings.key_empty': '请先输入密钥。',
 'app.settings.key_ok': '密钥已验证：CARTO 返回无水印瓦片。', 'app.settings.key_rejected': 'CARTO 拒绝了该密钥（HTTP {code}）。',
 'app.settings.key_unreachable': '无法连接 CARTO 进行验证。密钥已保存。',
 'app.settings.key_watermarked': '使用此密钥时 CARTO 仍返回带水印的瓦片。密钥可能未激活或受限。',
 'app.settings.xyz': '自定义瓦片服务器',
 'app.settings.xyz_note': '可选。任何你有权使用的 HTTPS XYZ 栅格瓦片源。请遵守其使用政策并注明来源。',
 'app.settings.xyz_url': '瓦片 URL 模板', 'app.settings.xyz_attr': '来源说明', 'app.settings.tile_cache': '手机上已缓存 {n} 个地图瓦片',
 'app.settings.projects': '项目', 'app.settings.export_project': '导出 .nrproj', 'app.settings.import_project': '导入 .nrproj',
 'app.settings.projects_note': '项目文件与 Windows 版 TimelinerX 兼容。时间轴数据本身绝不会包含在内。',
 'app.settings.device': '这部手机', 'app.settings.model': '型号', 'app.settings.hw': '硬件 ✓', 'app.settings.sw': '软件 ✓',
 'app.settings.unsupported': '不支持', 'app.settings.reset': '重置应用', 'app.settings.reset_q': '重置 TimelinerX？',
 'app.settings.reset_body': '将删除已导入的时间轴、项目和作品库列表。已在相册中的视频会保留。',
 'app.settings.project_loaded': '项目已载入。',
 'app.about.tagline': 'TimelinerX 把你的 Google 时间轴变成电影感地图视频，全部在你自己的手机上完成。',
 'app.about.privacy': '无账号、无上传、无追踪。时间轴只在这部手机上读取，绝不修改。只会下载地图瓦片，而且只在使用在线地图时下载。',
 'app.about.detail.import': '以流式方式读取 Android、iPhone 时间轴导出和 Google Takeout ZIP，大文件也很轻快。损坏的文件会保留每一条完整记录。',
 'app.about.detail.journey': '选择时段，去除 GPS 跳点，并把路线拆分为本地片段和长途旅程。航班会变成弧线。',
 'app.about.detail.camera': '规划每一帧镜头：缩放风格、到达时的构图、每段旅程的时长，并让屏幕上的速度保持均匀。与桌面版使用同一引擎。',
 'app.about.detail.tiles': '手机上的 Offline World 地图，或使用你密钥的 CARTO 瓦片。每个瓦片都经过主题的调色流程。',
 'app.about.detail.frames': '绘制每一帧：地图、已走过的路线、发光轨迹、标记（飞行时为飞机）、标题和日期条。',
 'app.about.detail.encode': '通过 Android MediaCodec 硬件编码 H.264，直接写入存储，长篇 4K 影片也能容纳。',
 'app.about.detail.verify': 'MP4 保存到 相册 › Movies › TimelinerX，并带缩略图出现在应用作品库中。',
 'app.about.credits': '时间轴解析、投影和镜头构图基于 mahlernim 的 Google Timeline Visualizer（MIT）。地图数据 © OpenStreetMap 贡献者 © CARTO。离线地图来自 Natural Earth（公共领域）。字体 Outfit 与 Instrument Sans（SIL OFL）。使用 Capacitor、Preact、fflate 和 mp4-muxer（MIT）构建。',
}

JA = {
 'app.nav.home': 'ホーム', 'app.nav.studio': 'スタジオ', 'app.nav.library': 'ライブラリ', 'app.nav.settings': '設定', 'app.nav.about': 'このアプリについて',
 'app.common.back': '戻る', 'app.common.cancel': 'キャンセル', 'app.common.close': '閉じる', 'app.common.days': '日', 'app.common.download': 'ダウンロード',
 'app.common.points': 'ポイント', 'app.common.remove': '削除', 'app.common.save': '保存', 'app.common.share': '共有', 'app.common.trips': '回の旅',
 'app.home.live': 'ライブレンダー', 'app.home.h1a': 'あなたの旅を、', 'app.home.h1b': '一本の映画に。',
 'app.home.lede': 'Google タイムラインを、スマホの中だけで映画のような地図動画に。プライベート、オフライン対応、アカウント不要。',
 'app.home.import': 'タイムラインを読み込む', 'app.home.demo': 'デモの旅を試す', 'app.home.p_local': 'スマホの外に出ない',
 'app.home.p_account': 'アカウント不要', 'app.home.p_offline': 'オフライン対応', 'app.home.continue': '続ける',
 'app.home.how_title': 'タイムラインの取り出し方', 'app.home.how_body': 'Android と iPhone の手順を順番に。', 'app.home.recent': '最近の動画',
 'app.demo.name': 'デモの旅', 'app.demo.title': 'ジャワ · バリ · パース',
 'app.demo.note': '合成デモデータ：スラバヤから列車でジャワ島を横断し、バリとパースへ飛行。',
 'app.import.local_note': 'ファイルはこのスマホで読み込まれ、アップロードされることはありません。', 'app.import.try_other': '別のファイルを選ぶ',
 'app.import.receive_failed': '共有されたファイルを読み込めませんでした。',
 'app.import.truncated': 'ファイルが途中で終わっています（不完全な可能性があります）。途切れる前の完全な記録はすべて読み込みました。',
 'app.import.skipped': '時刻または座標がない記録 {n} 件をスキップしました。',
 'app.err.not_json': 'このファイルはタイムラインのエクスポートではありません（JSON ではありません）。', 'app.err.unsupported': 'この JSON ファイルには Google タイムラインのデータが含まれていません。',
 'app.err.no_data': 'ファイルは読み込めましたが、使える位置情報がありません。', 'app.err.bad_zip': 'ZIP ファイルが壊れているか不完全です。',
 'app.err.no_json_in_zip': 'ZIP ファイルにタイムラインの JSON がありません。', 'app.err.empty': 'ファイルが空です。',
 'app.err.too_large': 'ファイルが大きすぎるか、展開すると危険な形式です。',
 'app.fmt.android': 'Android エクスポート', 'app.fmt.ios': 'iPhone エクスポート', 'app.fmt.takeout_semantic': 'Takeout（セマンティック）', 'app.fmt.takeout_records': 'Takeout（Records）',
 'app.analysis.title': 'タイムラインの準備ができました', 'app.analysis.build': '映画をつくる',
 'app.tutorial.intro': 'Google はタイムラインをスマホ本体に保存しているので、エクスポートはスマホの設定から始めます。',
 'app.tutorial.open_android': '保存した Timeline.json を TimelinerX で開くか、「タイムラインを読み込む」から選んでください。',
 'app.tutorial.open_iphone': 'ファイルを Android スマホに送り、TimelinerX で読み込んでください。',
 'app.tutorial.takeout_title': '古い Google Takeout のデータ？',
 'app.tutorial.takeout_body': 'takeout.google.com の .zip（2024 年以前）はそのまま使えます。Records.json や Semantic Location History も対応。',
 'app.studio.empty': 'タイムラインを読み込んで映画づくりを始めましょう。', 'app.studio.updating': '更新中…',
 'app.studio.world_fallback': 'CARTO キーが未設定のため、プレビューは Offline World マップを使っています。', 'app.studio.replace': 'タイムラインを差し替える',
 'app.studio.render': 'レンダー',
 'app.tab.journey': '旅', 'app.tab.camera': 'カメラ', 'app.tab.look': 'ルック', 'app.tab.titles': 'タイトル', 'app.tab.video': '動画',
 'app.journey.last7': '直近 7 日', 'app.journey.last30': '直近 30 日', 'app.journey.src_semantic': 'セマンティック', 'app.journey.src_detailed': '詳細',
 'app.journey.empty_period': 'この期間にはポイントがありません。タイムラインの範囲内の日付を選んでください。',
 'app.camera.fine': '微調整', 'app.look.theme': 'テーマ', 'app.look.trail': '軌跡とマーカー', 'app.look.film': 'フィルムルック',
 'app.map.auto': '自動', 'app.map.auto_carto': 'CARTO の道路地図（キー設定済み）', 'app.map.auto_world': 'CARTO キーを追加するまで Offline World',
 'app.map.world': 'Offline World', 'app.map.world_desc': '海岸線・国境・都市名をスマホ内に保存。ネットもキーも不要。',
 'app.map.carto': 'CARTO（テーマに合わせる）', 'app.map.carto_desc': '詳細な道路地図。テーマに合わせてライト／ダーク。',
 'app.map.carto_nokey': '無料の CARTO API キーが必要です（設定）。', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'カラフルな道路地図。',
 'app.map.plain': 'プレーン', 'app.map.plain_desc': '地図なし、経緯線グリッドのみ。ミニマルでオフライン。', 'app.map.xyz': 'カスタムタイルサーバー',
 'app.map.add_key': 'CARTO キーを追加', 'app.map.labels': '都市名',
 'app.titles.ribbon': '日付リボン',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'リール · TikTok', 'app.video.aspect_feed': 'フィード', 'app.video.hw': 'ハードウェアエンコーダー',
 'app.video.4k_warn': '4K は多くのメモリを使います。このスマホでは 1080p か 1440p が安全です。',
 'app.video.calm': 'ゆったり ≈ {s}', 'app.video.lively': 'テンポよく ≈ {s}',
 'app.audio.desc': '自分の音楽（MP3・AAC・WAV・OGG・FLAC）。動画より短い場合はループし、最後はフェードアウトします。',
 'app.audio.pick': '音楽を選ぶ', 'app.audio.bad': 'この音声ファイルはデコードできませんでした。',
 'app.render.title': '映画をレンダリング中', 'app.render.s_plan': 'カメラを計画中', 'app.render.s_tiles': '地図タイルを準備中',
 'app.render.s_audio': 'サウンドトラックをミックス中', 'app.render.s_frames': 'フレームをレンダリング・エンコード中', 'app.render.s_saving': 'ギャラリーに保存中',
 'app.render.eta': '残り {t}', 'app.render.keep_open': '{w}×{h}・{fps} fps。完了まで TimelinerX を開いたままにしてください。画面はオンのままです。',
 'app.render.cancel_q': 'レンダリングを停止しますか？', 'app.render.cancel_yes': '停止', 'app.render.cancel_no': '続ける',
 'app.render.done_title': '映画ができました', 'app.render.saved_gallery': 'ギャラリー › Movies › TimelinerX に保存しました。',
 'app.render.saved_browser': '完成しました。MP4 をダウンロードまたは共有できます。', 'app.render.speed': 'レンダー速度', 'app.render.open_player': '動画プレーヤーで開く',
 'app.render.back_studio': 'スタジオに戻る', 'app.render.cancelled': 'レンダリングを停止しました', 'app.render.failed': 'レンダリングに失敗しました', 'app.render.retry': 'もう一度',
 'app.render.no_encoder': 'このスマホはこのサイズの動画をエンコードできません。解像度かフレームレートを下げてください。',
 'app.render.nokey_title': 'CARTO には API キーが必要です',
 'app.render.nokey_body': 'キーがないと CARTO はすべてのタイルに「API KEY REQUIRED」と表示します。設定で無料キーを追加するか、Offline World マップでレンダリングしてください。',
 'app.render.use_world': 'Offline World マップを使う', 'app.render.tiles_failed_title': '一部の地図タイルがありません',
 'app.render.tiles_failed_body': '{total} 枚中 {n} 枚のタイルをダウンロードできませんでした。接続を確認するか、その部分は無地の背景で続行してください。',
 'app.render.continue_placeholder': 'このまま続ける',
 'app.library.sub': 'このスマホでレンダリングした映画。', 'app.library.empty': 'まだ映画はありません。スタジオで最初の一本をつくりましょう。',
 'app.library.reuse': 'この設定を再利用', 'app.library.remove_q': 'この動画を削除しますか？', 'app.library.remove_file': 'スマホとライブラリから削除',
 'app.library.remove_entry': 'ライブラリからのみ削除', 'app.library.delete_failed': '動画を削除できませんでした。',
 'app.library.applied': '設定をスタジオに読み込みました。',
 'app.settings.key_note': 'キーなしでリクエストしたタイルには CARTO が「API KEY REQUIRED」と表示します。個人・研究・非営利の利用ならキーは無料です。キーはこのスマホにだけ保存されます。',
 'app.settings.save_verify': '保存して確認', 'app.settings.get_key': '無料キーを取得', 'app.settings.key_empty': '先にキーを入力してください。',
 'app.settings.key_ok': 'キーを確認しました：CARTO は透かしなしのタイルを返します。', 'app.settings.key_rejected': 'CARTO がキーを拒否しました（HTTP {code}）。',
 'app.settings.key_unreachable': '確認のため CARTO に接続できませんでした。キーは保存済みです。',
 'app.settings.key_watermarked': 'このキーでも CARTO は透かし入りのタイルを返します。無効か制限付きの可能性があります。',
 'app.settings.xyz': 'カスタムタイルサーバー',
 'app.settings.xyz_note': '任意。利用を許可されている HTTPS の XYZ ラスターソースなら何でも。利用規約と帰属表示を守ってください。',
 'app.settings.xyz_url': 'タイル URL テンプレート', 'app.settings.xyz_attr': '帰属表示テキスト', 'app.settings.tile_cache': 'このスマホにキャッシュ済みの地図タイル：{n} 枚',
 'app.settings.projects': 'プロジェクト', 'app.settings.export_project': '.nrproj を書き出す', 'app.settings.import_project': '.nrproj を読み込む',
 'app.settings.projects_note': 'プロジェクトファイルは Windows 版 TimelinerX と互換性があります。タイムライン本体が含まれることはありません。',
 'app.settings.device': 'このスマホ', 'app.settings.model': '機種', 'app.settings.hw': 'ハードウェア ✓', 'app.settings.sw': 'ソフトウェア ✓',
 'app.settings.unsupported': '非対応', 'app.settings.reset': 'アプリをリセット', 'app.settings.reset_q': 'TimelinerX をリセットしますか？',
 'app.settings.reset_body': '読み込んだタイムライン、プロジェクト、ライブラリの一覧を削除します。ギャラリーにある動画は残ります。',
 'app.settings.project_loaded': 'プロジェクトを読み込みました。',
 'app.about.tagline': 'TimelinerX は Google タイムラインを、映画のような地図動画に変えます。すべてあなたのスマホの中で。',
 'app.about.privacy': 'アカウントなし、アップロードなし、追跡なし。タイムラインはこのスマホで読み込まれ、変更されることはありません。ダウンロードするのは地図タイルだけで、オンライン地図を使うときに限ります。',
 'app.about.detail.import': 'Android と iPhone のタイムラインのエクスポートや Google Takeout の ZIP をストリームで読み込むので、大きなファイルも軽快。壊れたファイルでも完全な記録はすべて残します。',
 'app.about.detail.journey': '期間を選び、GPS の瞬間移動ノイズを除き、ルートを近場のエピソードと長距離の旅に分けます。フライトは弧になります。',
 'app.about.detail.camera': 'カメラの全フレームを計画：ズームスタイル、到着時の構図、旅ごとの時間、そして画面上の速度をならします。デスクトップ版と同じエンジンです。',
 'app.about.detail.tiles': 'スマホ内の Offline World マップ、またはあなたのキーでの CARTO タイル。すべてのタイルがテーマのカラーグレーディングを通ります。',
 'app.about.detail.frames': '各フレームを描画：地図、通ったルート、光る軌跡、マーカー（飛行中は飛行機）、タイトル、日付リボン。',
 'app.about.detail.encode': 'Android MediaCodec によるハードウェア H.264 エンコード。ストレージへ直接書き込むので、長い 4K 映画も収まります。',
 'app.about.detail.verify': 'MP4 はギャラリー › Movies › TimelinerX と、サムネイル付きでアプリのライブラリに入ります。',
 'app.about.credits': 'タイムライン解析、投影、カメラの構図は mahlernim の Google Timeline Visualizer（MIT）を基にしています。地図データ © OpenStreetMap 貢献者 © CARTO。オフライン地図は Natural Earth（パブリックドメイン）。フォント Outfit・Instrument Sans（SIL OFL）。Capacitor、Preact、fflate、mp4-muxer（MIT）で構築。',
}
