RU = {
 'app.nav.home': 'Главная', 'app.nav.studio': 'Студия', 'app.nav.library': 'Медиатека', 'app.nav.settings': 'Настройки', 'app.nav.about': 'О приложении',
 'app.common.back': 'Назад', 'app.common.cancel': 'Отмена', 'app.common.close': 'Закрыть', 'app.common.days': 'дн.', 'app.common.download': 'Скачать',
 'app.common.points': 'точек', 'app.common.remove': 'Удалить', 'app.common.save': 'Сохранить', 'app.common.share': 'Поделиться', 'app.common.trips': 'поездок',
 'app.home.live': 'РЕНДЕР В РЕАЛЬНОМ ВРЕМЕНИ', 'app.home.h1a': 'Ваши путешествия —', 'app.home.h1b': 'в кино.',
 'app.home.lede': 'Превратите Хронологию Google в кинематографичное видео с картой прямо на телефоне. Приватно, работает офлайн, без аккаунта.',
 'app.home.import': 'Импортировать Хронологию', 'app.home.demo': 'Посмотреть демо-путешествие', 'app.home.p_local': 'Остаётся на телефоне',
 'app.home.p_account': 'Без аккаунта', 'app.home.p_offline': 'Работает офлайн', 'app.home.continue': 'Продолжить',
 'app.home.how_title': 'Как получить Хронологию', 'app.home.how_body': 'Пошагово для Android и iPhone.', 'app.home.recent': 'Недавние видео',
 'app.demo.name': 'Демо-путешествие', 'app.demo.title': 'Ява · Бали · Перт',
 'app.demo.note': 'Синтетические демо-данные: из Сурабаи на поезде через Яву, затем перелёты на Бали и в Перт.',
 'app.import.local_note': 'Файл читается на этом телефоне и никуда не загружается.', 'app.import.try_other': 'Выбрать другой файл',
 'app.import.receive_failed': 'Не удалось прочитать переданный файл.',
 'app.import.truncated': 'Файл обрывается (возможно, он неполный). Все целые записи до обрыва импортированы.',
 'app.import.skipped': 'Записей пропущено: {n} (нет времени или координат).',
 'app.err.not_json': 'Это не экспорт Хронологии (файл не в формате JSON).', 'app.err.unsupported': 'В этом JSON-файле нет данных Хронологии Google.',
 'app.err.no_data': 'Файл прочитан, но в нём нет пригодных точек местоположения.', 'app.err.bad_zip': 'ZIP-архив повреждён или неполон.',
 'app.err.no_json_in_zip': 'В ZIP-архиве нет JSON Хронологии.', 'app.err.empty': 'Файл пуст.',
 'app.err.too_large': 'Файл слишком большой или небезопасен для распаковки.',
 'app.fmt.android': 'Экспорт Android', 'app.fmt.ios': 'Экспорт iPhone', 'app.fmt.takeout_semantic': 'Takeout (семантика)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'Хронология готова', 'app.analysis.build': 'Создать мой фильм',
 'app.tutorial.intro': 'Google хранит Хронологию на телефоне, поэтому экспорт начинается в настройках телефона.',
 'app.tutorial.open_android': 'Откройте сохранённый Timeline.json в TimelinerX или нажмите «Импортировать Хронологию» и выберите его.',
 'app.tutorial.open_iphone': 'Отправьте файл на свой Android-телефон и импортируйте его в TimelinerX.',
 'app.tutorial.takeout_title': 'Старый экспорт Google Takeout?',
 'app.tutorial.takeout_body': 'ZIP с takeout.google.com (до 2024 года) подходит как есть, включая Records.json и Semantic Location History.',
 'app.studio.empty': 'Импортируйте Хронологию, чтобы начать фильм.', 'app.studio.updating': 'Обновление…',
 'app.studio.world_fallback': 'Превью использует карту Offline World, потому что ключ CARTO не задан.', 'app.studio.replace': 'Заменить Хронологию',
 'app.studio.render': 'Рендер',
 'app.tab.journey': 'Маршрут', 'app.tab.camera': 'Камера', 'app.tab.look': 'Стиль', 'app.tab.titles': 'Титры', 'app.tab.video': 'Видео',
 'app.journey.last7': 'Последние 7 дней', 'app.journey.last30': 'Последние 30 дней', 'app.journey.src_semantic': 'Семантический', 'app.journey.src_detailed': 'Подробный',
 'app.journey.empty_period': 'В этом периоде нет точек. Выберите даты в пределах Хронологии.',
 'app.camera.fine': 'Тонкая настройка', 'app.look.theme': 'Тема', 'app.look.trail': 'След и маркер', 'app.look.film': 'Киноэффекты',
 'app.map.auto': 'Автоматически', 'app.map.auto_carto': 'Улицы CARTO (ключ задан)', 'app.map.auto_world': 'Offline World, пока не добавлен ключ CARTO',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'Береговые линии, границы и названия городов хранятся на телефоне. Без интернета и ключа.',
 'app.map.carto': 'CARTO (по теме)', 'app.map.carto_desc': 'Подробная карта улиц, светлая или тёмная в тон теме.',
 'app.map.carto_nokey': 'Нужен бесплатный API-ключ CARTO (Настройки).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'Цветная карта улиц.',
 'app.map.plain': 'Простой фон', 'app.map.plain_desc': 'Без карты, только координатная сетка. Минимально и офлайн.', 'app.map.xyz': 'Свой сервер тайлов',
 'app.map.add_key': 'Добавить ключ CARTO', 'app.map.labels': 'Названия городов',
 'app.titles.ribbon': 'Лента дат',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'Лента', 'app.video.hw': 'аппаратный кодек',
 'app.video.4k_warn': '4K требует много памяти. На этом телефоне надёжнее выбрать 1080p или 1440p.',
 'app.video.calm': 'Спокойно ≈ {s}', 'app.video.lively': 'Динамично ≈ {s}',
 'app.audio.desc': 'Ваша музыка (MP3, AAC, WAV, OGG, FLAC). Если она короче видео, она зацикливается, а в конце плавно затихает.',
 'app.audio.pick': 'Выбрать музыку', 'app.audio.bad': 'Не удалось декодировать этот аудиофайл.',
 'app.render.title': 'Рендер фильма', 'app.render.s_plan': 'Планирование камеры', 'app.render.s_tiles': 'Подготовка тайлов карты',
 'app.render.s_audio': 'Сведение саундтрека', 'app.render.s_frames': 'Рендер и кодирование кадров', 'app.render.s_saving': 'Сохранение в галерею',
 'app.render.eta': 'осталось {t}', 'app.render.keep_open': '{w}×{h}, {fps} кадр/с. Не закрывайте TimelinerX до конца. Экран не погаснет.',
 'app.render.cancel_q': 'Остановить рендер?', 'app.render.cancel_yes': 'Остановить', 'app.render.cancel_no': 'Продолжить рендер',
 'app.render.done_title': 'Фильм готов', 'app.render.saved_gallery': 'Сохранено: Галерея › Movies › TimelinerX.',
 'app.render.saved_browser': 'Готово. Скачайте MP4 или поделитесь им.', 'app.render.speed': 'скорость рендера', 'app.render.open_player': 'Открыть в видеоплеере',
 'app.render.back_studio': 'Вернуться в студию', 'app.render.cancelled': 'Рендер остановлен', 'app.render.failed': 'Ошибка рендера', 'app.render.retry': 'Повторить',
 'app.render.no_encoder': 'Этот телефон не может кодировать видео такого размера. Выберите меньшее разрешение или частоту кадров.',
 'app.render.nokey_title': 'Для CARTO нужен API-ключ',
 'app.render.nokey_body': 'Без ключа CARTO ставит на каждый тайл надпись «API KEY REQUIRED». Добавьте бесплатный ключ в настройках или рендерите с картой Offline World.',
 'app.render.use_world': 'Использовать карту Offline World', 'app.render.tiles_failed_title': 'Не хватает тайлов карты',
 'app.render.tiles_failed_body': 'Не удалось загрузить {n} из {total} тайлов. Проверьте подключение или продолжите с простым фоном в этих местах.',
 'app.render.continue_placeholder': 'Всё равно продолжить',
 'app.library.sub': 'Фильмы, созданные на этом телефоне.', 'app.library.empty': 'Фильмов пока нет. Создайте первый в студии.',
 'app.library.reuse': 'Использовать эти настройки', 'app.library.remove_q': 'Удалить это видео?', 'app.library.remove_file': 'Удалить с телефона и из медиатеки',
 'app.library.remove_entry': 'Убрать только из медиатеки', 'app.library.delete_failed': 'Не удалось удалить видео.',
 'app.library.applied': 'Настройки загружены в студию.',
 'app.settings.key_note': 'CARTO ставит надпись «API KEY REQUIRED» на тайлы, запрошенные без ключа. Ключ бесплатен для личного, научного и некоммерческого использования. Ключ хранится только на этом телефоне.',
 'app.settings.save_verify': 'Сохранить и проверить', 'app.settings.get_key': 'Получить бесплатный ключ', 'app.settings.key_empty': 'Сначала введите ключ.',
 'app.settings.key_ok': 'Ключ проверен: CARTO отдаёт чистые тайлы.', 'app.settings.key_rejected': 'CARTO отклонил ключ (HTTP {code}).',
 'app.settings.key_unreachable': 'Не удалось связаться с CARTO для проверки. Ключ сохранён.',
 'app.settings.key_watermarked': 'С этим ключом CARTO по-прежнему отдаёт тайлы с водяным знаком. Возможно, ключ не активен или ограничен.',
 'app.settings.xyz': 'Свой сервер тайлов',
 'app.settings.xyz_note': 'Необязательно. Любой растровый XYZ-источник по HTTPS, которым вам разрешено пользоваться. Соблюдайте его правила и указывайте авторство.',
 'app.settings.xyz_url': 'Шаблон URL тайлов', 'app.settings.xyz_attr': 'Текст авторства', 'app.settings.tile_cache': 'Тайлов карты в кэше: {n}',
 'app.settings.projects': 'Проекты', 'app.settings.export_project': 'Экспорт .nrproj', 'app.settings.import_project': 'Импорт .nrproj',
 'app.settings.projects_note': 'Файлы проектов совместимы с TimelinerX для Windows. Сама Хронология в них никогда не попадает.',
 'app.settings.device': 'Этот телефон', 'app.settings.model': 'Модель', 'app.settings.hw': 'аппаратно ✓', 'app.settings.sw': 'программно ✓',
 'app.settings.unsupported': 'не поддерживается', 'app.settings.reset': 'Сбросить приложение', 'app.settings.reset_q': 'Сбросить TimelinerX?',
 'app.settings.reset_body': 'Удаляет импортированную Хронологию, проект и список медиатеки. Видео в галерее остаются.',
 'app.settings.project_loaded': 'Проект загружен.',
 'app.about.tagline': 'TimelinerX превращает Хронологию Google в кинематографичное видео с картой, полностью на вашем телефоне.',
 'app.about.privacy': 'Без аккаунта, без загрузок, без слежки. Хронология читается на этом телефоне и никогда не изменяется. Загружаются только тайлы карты и только при использовании онлайн-карты.',
 'app.about.detail.import': 'Читает экспорт Хронологии с Android и iPhone и ZIP из Google Takeout потоком, поэтому большие файлы не тормозят. Из повреждённых файлов сохраняется каждая целая запись.',
 'app.about.detail.journey': 'Выбирает период, убирает скачки GPS и делит маршрут на локальные эпизоды и дальние поездки. Перелёты становятся дугами.',
 'app.about.detail.camera': 'Планирует каждый кадр камеры: стиль зума, кадрирование по прибытии, время на поездку и равномерную скорость на экране. Тот же движок, что и в настольной версии.',
 'app.about.detail.tiles': 'Карта Offline World на телефоне или тайлы CARTO с вашим ключом. Каждый тайл проходит цветокоррекцию темы.',
 'app.about.detail.frames': 'Рисует каждый кадр: карту, пройденный маршрут, светящийся след, маркер (самолёт на перелётах), титры и ленту дат.',
 'app.about.detail.encode': 'Аппаратное кодирование H.264 через Android MediaCodec с записью прямо в хранилище, поэтому помещаются даже длинные фильмы в 4K.',
 'app.about.detail.verify': 'MP4 появляется в Галерее › Movies › TimelinerX и в медиатеке приложения с миниатюрой.',
 'app.about.credits': 'Разбор Хронологии, проекция и кадрирование камеры основаны на Google Timeline Visualizer от mahlernim (MIT). Картографические данные © участники OpenStreetMap © CARTO. Офлайн-карта на основе Natural Earth (общественное достояние). Шрифты Outfit и Instrument Sans (SIL OFL). Создано с Capacitor, Preact, fflate и mp4-muxer (MIT).',
}

AR = {
 'app.nav.home': 'الرئيسية', 'app.nav.studio': 'الاستوديو', 'app.nav.library': 'المكتبة', 'app.nav.settings': 'الإعدادات', 'app.nav.about': 'حول',
 'app.common.back': 'رجوع', 'app.common.cancel': 'إلغاء', 'app.common.close': 'إغلاق', 'app.common.days': 'يوم', 'app.common.download': 'تنزيل',
 'app.common.points': 'نقطة', 'app.common.remove': 'إزالة', 'app.common.save': 'حفظ', 'app.common.share': 'مشاركة', 'app.common.trips': 'رحلة',
 'app.home.live': 'عرض مباشر', 'app.home.h1a': 'رحلاتك،', 'app.home.h1b': 'في فيلم.',
 'app.home.lede': 'حوّل مخطط Google الزمني إلى فيديو خرائط سينمائي على هاتفك مباشرة. خاص، يعمل دون اتصال، بلا حساب.',
 'app.home.import': 'استيراد المخطط الزمني', 'app.home.demo': 'جرّب الرحلة التجريبية', 'app.home.p_local': 'يبقى على هاتفك',
 'app.home.p_account': 'بلا حساب', 'app.home.p_offline': 'يعمل دون اتصال', 'app.home.continue': 'متابعة',
 'app.home.how_title': 'الحصول على المخطط الزمني', 'app.home.how_body': 'خطوة بخطوة لأندرويد وآيفون.', 'app.home.recent': 'أحدث الفيديوهات',
 'app.demo.name': 'رحلة تجريبية', 'app.demo.title': 'جاوة · بالي · بيرث',
 'app.demo.note': 'بيانات تجريبية مُصطنعة: من سورابايا بالقطار عبر جاوة، ثم رحلات جوية إلى بالي وبيرث.',
 'app.import.local_note': 'يُقرأ الملف على هذا الهاتف ولا يُرفع أبدًا.', 'app.import.try_other': 'اختر ملفًا آخر',
 'app.import.receive_failed': 'تعذّرت قراءة الملف المُشارَك.',
 'app.import.truncated': 'ينتهي الملف فجأة (قد يكون ناقصًا). تم استيراد كل السجلات الكاملة قبل الانقطاع.',
 'app.import.skipped': 'تم تخطي سجلات غير صالحة (بلا وقت أو إحداثيات): {n}.',
 'app.err.not_json': 'هذا الملف ليس تصديرًا للمخطط الزمني (ليس JSON).', 'app.err.unsupported': 'ملف JSON هذا لا يحتوي على بيانات مخطط Google الزمني.',
 'app.err.no_data': 'تمت قراءة الملف، لكنه لا يحتوي على نقاط موقع صالحة.', 'app.err.bad_zip': 'ملف ZIP تالف أو غير مكتمل.',
 'app.err.no_json_in_zip': 'ملف ZIP لا يحتوي على JSON للمخطط الزمني.', 'app.err.empty': 'الملف فارغ.',
 'app.err.too_large': 'الملف كبير جدًا أو غير آمن لفك ضغطه.',
 'app.fmt.android': 'تصدير أندرويد', 'app.fmt.ios': 'تصدير آيفون', 'app.fmt.takeout_semantic': 'Takeout (دلالي)', 'app.fmt.takeout_records': 'Takeout (Records)',
 'app.analysis.title': 'مخططك الزمني جاهز', 'app.analysis.build': 'اصنع فيلمي',
 'app.tutorial.intro': 'يحتفظ Google بالمخطط الزمني على هاتفك، لذا يبدأ التصدير من إعدادات الهاتف.',
 'app.tutorial.open_android': 'افتح ملف Timeline.json المحفوظ باستخدام TimelinerX، أو اضغط «استيراد المخطط الزمني» واختره.',
 'app.tutorial.open_iphone': 'أرسل الملف إلى هاتف أندرويد، ثم استورده في TimelinerX.',
 'app.tutorial.takeout_title': 'لديك تصدير قديم من Google Takeout؟',
 'app.tutorial.takeout_body': 'ملف ‎.zip من takeout.google.com (قبل 2024) يعمل كما هو، بما في ذلك Records.json و Semantic Location History.',
 'app.studio.empty': 'استورد مخططًا زمنيًا لتبدأ فيلمك.', 'app.studio.updating': 'جارٍ التحديث…',
 'app.studio.world_fallback': 'تستخدم المعاينة خريطة Offline World لأنه لم يُضبط مفتاح CARTO.', 'app.studio.replace': 'استبدال المخطط الزمني',
 'app.studio.render': 'تصيير',
 'app.tab.journey': 'الرحلة', 'app.tab.camera': 'الكاميرا', 'app.tab.look': 'المظهر', 'app.tab.titles': 'العناوين', 'app.tab.video': 'الفيديو',
 'app.journey.last7': 'آخر 7 أيام', 'app.journey.last30': 'آخر 30 يومًا', 'app.journey.src_semantic': 'دلالي', 'app.journey.src_detailed': 'تفصيلي',
 'app.journey.empty_period': 'لا توجد نقاط في هذه الفترة. اختر تواريخ ضمن مخططك الزمني.',
 'app.camera.fine': 'ضبط دقيق', 'app.look.theme': 'السمة', 'app.look.trail': 'الأثر والعلامة', 'app.look.film': 'مظهر سينمائي',
 'app.map.auto': 'تلقائي', 'app.map.auto_carto': 'شوارع CARTO (المفتاح مضبوط)', 'app.map.auto_world': 'Offline World حتى تضيف مفتاح CARTO',
 'app.map.world': 'Offline World', 'app.map.world_desc': 'السواحل والحدود وأسماء المدن مخزنة على الهاتف. بلا إنترنت وبلا مفتاح.',
 'app.map.carto': 'CARTO (حسب السمة)', 'app.map.carto_desc': 'خريطة شوارع مفصلة، فاتحة أو داكنة حسب السمة.',
 'app.map.carto_nokey': 'تحتاج إلى مفتاح CARTO API مجاني (الإعدادات).', 'app.map.voyager': 'CARTO Voyager', 'app.map.voyager_desc': 'خريطة شوارع ملوّنة.',
 'app.map.plain': 'خلفية بسيطة', 'app.map.plain_desc': 'بلا خريطة، شبكة إحداثيات فقط. بسيطة وتعمل دون اتصال.', 'app.map.xyz': 'خادم بلاطات مخصص',
 'app.map.add_key': 'إضافة مفتاح CARTO', 'app.map.labels': 'أسماء المدن',
 'app.titles.ribbon': 'شريط التاريخ',
 'app.video.aspect_yt': 'YouTube', 'app.video.aspect_reels': 'Reels · TikTok', 'app.video.aspect_feed': 'الموجز', 'app.video.hw': 'ترميز عتادي',
 'app.video.4k_warn': 'يتطلب 4K ذاكرة كبيرة. على هذا الهاتف، 1080p أو 1440p خيار أكثر أمانًا.',
 'app.video.calm': 'هادئ ≈ {s}', 'app.video.lively': 'حيوي ≈ {s}',
 'app.audio.desc': 'موسيقاك الخاصة (MP3، AAC، WAV، OGG، FLAC). تتكرر إن كانت أقصر من الفيديو وتتلاشى في النهاية.',
 'app.audio.pick': 'اختر موسيقى', 'app.audio.bad': 'تعذّر فك ترميز ملف الصوت هذا.',
 'app.render.title': 'جارٍ تصيير فيلمك', 'app.render.s_plan': 'تخطيط الكاميرا', 'app.render.s_tiles': 'تجهيز بلاطات الخريطة',
 'app.render.s_audio': 'مزج الموسيقى التصويرية', 'app.render.s_frames': 'تصيير الإطارات وترميزها', 'app.render.s_saving': 'الحفظ في المعرض',
 'app.render.eta': 'متبقٍ {t}', 'app.render.keep_open': '{w}×{h} بمعدل {fps} إطار/ث. أبقِ TimelinerX مفتوحًا حتى النهاية. ستبقى الشاشة مضاءة.',
 'app.render.cancel_q': 'إيقاف التصيير؟', 'app.render.cancel_yes': 'إيقاف', 'app.render.cancel_no': 'متابعة التصيير',
 'app.render.done_title': 'فيلمك جاهز', 'app.render.saved_gallery': 'تم الحفظ في المعرض › Movies › TimelinerX.',
 'app.render.saved_browser': 'جاهز. نزّل ملف MP4 أو شاركه.', 'app.render.speed': 'سرعة التصيير', 'app.render.open_player': 'فتح في مشغّل الفيديو',
 'app.render.back_studio': 'العودة إلى الاستوديو', 'app.render.cancelled': 'توقف التصيير', 'app.render.failed': 'فشل التصيير', 'app.render.retry': 'إعادة المحاولة',
 'app.render.no_encoder': 'لا يستطيع هذا الهاتف ترميز فيديو بهذا الحجم. اختر دقة أو معدل إطارات أقل.',
 'app.render.nokey_title': 'تحتاج CARTO إلى مفتاح API',
 'app.render.nokey_body': 'دون مفتاح تختم CARTO كل بلاطة بعبارة «API KEY REQUIRED». أضف مفتاحًا مجانيًا في الإعدادات، أو صيّر باستخدام خريطة Offline World.',
 'app.render.use_world': 'استخدام خريطة Offline World', 'app.render.tiles_failed_title': 'بعض بلاطات الخريطة مفقودة',
 'app.render.tiles_failed_body': 'تعذّر تنزيل {n} من أصل {total} بلاطة. تحقق من الاتصال، أو تابع بخلفية بسيطة في تلك المواضع.',
 'app.render.continue_placeholder': 'المتابعة على أي حال',
 'app.library.sub': 'أفلام صُيّرت على هذا الهاتف.', 'app.library.empty': 'لا توجد أفلام بعد. صيّر أول فيلم في الاستوديو.',
 'app.library.reuse': 'إعادة استخدام هذه الإعدادات', 'app.library.remove_q': 'إزالة هذا الفيديو؟', 'app.library.remove_file': 'حذف من الهاتف والمكتبة',
 'app.library.remove_entry': 'إزالة من المكتبة فقط', 'app.library.delete_failed': 'تعذّر حذف الفيديو.',
 'app.library.applied': 'تم تحميل الإعدادات في الاستوديو.',
 'app.settings.key_note': 'تختم CARTO عبارة «API KEY REQUIRED» على البلاطات المطلوبة دون مفتاح. المفاتيح مجانية للاستخدام الشخصي والبحثي وغير الربحي. يُحفظ مفتاحك على هذا الهاتف فقط.',
 'app.settings.save_verify': 'حفظ وتحقق', 'app.settings.get_key': 'احصل على مفتاح مجاني', 'app.settings.key_empty': 'أدخل مفتاحًا أولًا.',
 'app.settings.key_ok': 'تم التحقق من المفتاح: تعيد CARTO بلاطات نظيفة.', 'app.settings.key_rejected': 'رفضت CARTO المفتاح (HTTP {code}).',
 'app.settings.key_unreachable': 'تعذّر الوصول إلى CARTO للتحقق. تم حفظ المفتاح.',
 'app.settings.key_watermarked': 'ما زالت CARTO تعيد بلاطات بعلامة مائية مع هذا المفتاح. قد يكون غير مفعّل أو مقيّدًا.',
 'app.settings.xyz': 'خادم بلاطات مخصص',
 'app.settings.xyz_note': 'اختياري. أي مصدر XYZ نقطي عبر HTTPS يُسمح لك باستخدامه. التزم بسياسة الاستخدام والإسناد.',
 'app.settings.xyz_url': 'قالب رابط البلاطات', 'app.settings.xyz_attr': 'نص الإسناد', 'app.settings.tile_cache': 'بلاطات مخزنة مؤقتًا على الهاتف: {n}',
 'app.settings.projects': 'المشاريع', 'app.settings.export_project': 'تصدير ‎.nrproj', 'app.settings.import_project': 'استيراد ‎.nrproj',
 'app.settings.projects_note': 'ملفات المشاريع متوافقة مع TimelinerX لويندوز. لا يُضمَّن المخطط الزمني نفسه أبدًا.',
 'app.settings.device': 'هذا الهاتف', 'app.settings.model': 'الطراز', 'app.settings.hw': 'عتادي ✓', 'app.settings.sw': 'برمجي ✓',
 'app.settings.unsupported': 'غير مدعوم', 'app.settings.reset': 'إعادة ضبط التطبيق', 'app.settings.reset_q': 'إعادة ضبط TimelinerX؟',
 'app.settings.reset_body': 'يزيل المخطط الزمني المستورد والمشروع وقائمة المكتبة. تبقى الفيديوهات الموجودة في معرضك.',
 'app.settings.project_loaded': 'تم تحميل المشروع.',
 'app.about.tagline': 'يحوّل TimelinerX مخطط Google الزمني إلى فيديو خرائط سينمائي، بالكامل على هاتفك.',
 'app.about.privacy': 'بلا حساب ولا رفع ولا تتبع. يُقرأ مخططك الزمني على هذا الهاتف ولا يُعدَّل أبدًا. لا تُنزَّل إلا بلاطات الخريطة، وفقط عند استخدام خريطة متصلة.',
 'app.about.detail.import': 'يقرأ تصديرات المخطط الزمني من أندرويد وآيفون وملفات ZIP من Google Takeout كتدفق، فتبقى الملفات الكبيرة خفيفة. تحتفظ الملفات التالفة بكل سجل كامل.',
 'app.about.detail.journey': 'يختار الفترة ويزيل قفزات GPS ويقسّم المسار إلى حلقات محلية ورحلات طويلة. تتحول الرحلات الجوية إلى أقواس.',
 'app.about.detail.camera': 'يخطط كل إطار للكاميرا: نمط التكبير، والتأطير عند الوصول، والوقت لكل رحلة، ثم يوحّد السرعة على الشاشة. المحرك نفسه في تطبيق سطح المكتب.',
 'app.about.detail.tiles': 'خريطة Offline World على الهاتف، أو بلاطات CARTO بمفتاحك. تمر كل بلاطة عبر معالجة ألوان السمة.',
 'app.about.detail.frames': 'يرسم كل إطار: الخريطة والمسار المقطوع والأثر المضيء والعلامة (طائرة أثناء الطيران) والعناوين وشريط التاريخ.',
 'app.about.detail.encode': 'ترميز H.264 عتادي عبر Android MediaCodec يُكتب مباشرة إلى التخزين، فتتسع حتى أفلام 4K الطويلة.',
 'app.about.detail.verify': 'يصل ملف MP4 إلى المعرض › Movies › TimelinerX وإلى مكتبة التطبيق مع صورة مصغّرة.',
 'app.about.credits': 'تحليل المخطط الزمني والإسقاط وتأطير الكاميرا مبنية على Google Timeline Visualizer من mahlernim (MIT). بيانات الخرائط © مساهمو OpenStreetMap © CARTO. الخريطة دون اتصال من Natural Earth (ملكية عامة). الخطوط Outfit و Instrument Sans (SIL OFL). بُني باستخدام Capacitor و Preact و fflate و mp4-muxer (MIT).',
}
